### ISSUE TITLE
feat: Showing an image on callkit / answer activity

### ISSUE THREAD

**Issue by cybex-dev** [cybex-dev/twilio_voice#103]
This is a feature I'm currently working on - interested to know if I should adapt for a PR.

## Description:
Upon receiving a call, call parameters are presented. Using call parameters, set aside reserved parameter names used for UI configuration.

- `CALLER_ID`: (domain specific) ID of caller e.g. Firebase user Id.
- `CALLER_NAME`: Display name of individual placing the call.
- `CALLER_AVATAR_URL`: URL of image (person, or other).

These will be used in configuring the UI per platform.

* ### iOS

Configure Callkit with Display Name & loading avatar URL. To do this, a new contact needs to be created, as described [how-to-show-caller-image-on-ios-native-ui-call-by-using-callkit-framework](https://stackoverflow.com/questions/41735257/how-to-show-caller-image-on-ios-native-ui-call-by-using-callkit-framework). This will show an image as a background to the CallKit - great feature, strange implementation due to the contact creation requirement.

* ### Android

Configure UI with
 
 * Display name
 * App Name
 * (optional) URL image (loaded as background image (fit: Cover)

#### Further additions:
Customised Android CallScreen UIs. As with the `flutter_stripe` package, they offer alot of UI customization per platform natively in Flutter (passed onto the individual platform). This isn't useful to iOS due to its CallKit, but one can provide some level of customisation to Android screens, limited by substantial replicating typical Incoming call / Ongoing call screens.

Are you interested in any of these additions?

**Comment by diegogarciar** [comment]
sounds great! Looking forward to it!

**Comment by Yahllil** [comment]
Any update on this one?

**Comment by cybex-dev** [comment]
@diegogarciar I'll be making a few PR's during the course of the week and the next, starting 'tomorrow' addressing a few issues and key/missing features. 

- current issue (feature)
- custom audio device support / bluetooth integration
- "more" customisable Android call screen
- iOS callkit integration with URL (interpret call parameters, etc for twilio_voice -> callkit specific display data, i.e. thumbnails)
- web integration/support
- a few bug fixes, etc

As a heads up, and a kind request - if possible ofcourse, could you expedite these PRs.

**Comment by diegogarciar** [comment]
Will do!

**Comment by cybex-dev** [comment]
#129
