### ISSUE TITLE
call success but getting From null and To null and when connecting call getting url music playing continuously 

### ISSUE THREAD

**Issue by Raj-impetrosys** [cybex-dev/twilio_voice#104]
<img width="1440" alt="Screenshot 2022-09-14 at 5 14 15 PM" src="https://user-images.githubusercontent.com/83710343/190145037-ad315c6d-5fc1-4249-bbdd-9ee9d75532ac.png">
<img width="1440" alt="Screenshot 2022-09-14 at 5 14 22 PM" src="https://user-images.githubusercontent.com/83710343/190145113-41536565-8570-480d-a3b4-e0fe8b40e3b0.png">

how can i solve to get my voice instead of mp3 used in twiml app

**Comment by cybex-dev** [comment]
@Raj-impetrosys see https://github.com/diegogarciar/twilio_voice/issues/105#issuecomment-1260941399, could be useful.

**Comment by cybex-dev** [comment]
Closing due top lack of responses, feedback or activity.
