### ISSUE TITLE
RECONNECTING Status and Callee event not work on Caller side

### ISSUE THREAD

**Issue by Ahmadgnoor** [cybex-dev/twilio_voice#105]
Please set the reconnecting flow 
Also If Callee end the call or Answer the call there is no event on Caller side 
Please guid me for that

**Comment by cybex-dev** [comment]
> Also If Callee end the call or Answer the call there is no event on Caller side
It seems documentation may be lacking on this side. I'll post PR to update it.

> Please set the reconnecting flow
There is no reconnecting/status available atm, however I'll look to post a PR for this too.

Current (normal call, followed by hang up) flow is as follows.

**Start**
- Caller: Ringing (no call params available)
- Callee: Ringing (call params available)

**Transition to answer**
- Caller: Ringing (no call params available)
- Callee: Answer (call params available)

**Connected:**
_Assuming you're using `answerOnBridge` (highly recommended)_
- Caller: Connected (no call params available)
- Callee: Connected (no call params available)

**End**
- Caller: Connected (no call params available)
- Callee: Connected (no call params available)

**Comment by Ahmadgnoor** [comment]
Thank you for your reply first

i just need an event because  when i answer the Call or reject the call by Callee then the Customer (Caller) is not getting any event or status by plugin. Also if during Call the  Callee remove the App from memory after minimize Also Caller side not be able to listen / Receive any event and remain idle on that side and after time end call manually... 
also If internet not working correctly plugin not be able to reconnect the call ... just seem call not working ...

If Caller end then there is no issue Callee receive event, working fine ...

Hope you understand my problem and do something for me...

**Comment by cybex-dev** [comment]
I'm working on a major upgrade for Twilio Voice to address these issues including several upgrades / feature additions (this is purely for my own needs, but I'm sure many others would find it useful). Eta ~1-2mo from now.

**Comment by Ahmadgnoor** [comment]
ok thank you ...
