### ISSUE TITLE
App Crashes In iOS(Duplicate plugin key: twilio_voice)

### ISSUE THREAD

**Issue by fthardik** [cybex-dev/twilio_voice#106]
Hello,

I have used sdk: ">=2.12.0 <3.0.0" version and I can't able to run iOS apps. It's open and crashes for the below reason. If I comment twilio_voice lib and run, it worked perfectly but after adding this library iOS app continuously crashes.

You can see here crash detail.
![image](https://user-images.githubusercontent.com/115221615/194526028-fee6842d-9300-4367-ae3e-630d38a1a0e5.png)

It working perfectly with sdk: ">=2.7.0 <3.0.0" but using sdk: ">=2.12.0 <3.0.0" null safety it crash on iOS. Please let me know how can I solve it.

**Comment by kashiftariq1997** [comment]
@fthardik Hi did you find any solution for this issue

**Comment by fthardik** [comment]
> @fthardik Hi did you find any solution for this issue

Are you using a background locator service or lib?

**Comment by cybex-dev** [comment]
@fthardik thanks for the testing and info, I'll look into getting a fix out for you.
