### ISSUE TITLE
Question: How to make it use iOS CallKit

### ISSUE THREAD

**Issue by agreensh** [cybex-dev/twilio_voice#11]
I can make Twilio calls, but on iOS it is not using CallKit.
I notice in the example, a Flutter screen is pushed during calls, but looking at the 
iOS code (for the plugin) it seems to be integrated with CallKit.
Do I have to set any parameters in the code, or add anything to the iOS project (I've already set 'Audio, Airplay, and Picture in Picture' and 'Voice over IP' in the Info.plist).

**Comment by diegogarciar** [comment]
Hello, have you provided the proper certificates to twilio's dashboard?

Best,
Diego

**Comment by agreensh** [comment]
Yes, all certificates are are correct. I already have a (Swift) iOS app using the same Twilio server, and that is showing the CallKit UI correctly - I am trying to migrate this app to Flutter.

**Comment by diegogarciar** [comment]
well that's strange then, If you already know how to setup for native, Flutter is no different.
So you are already calling your server to register your user?

Maybe try running the flutter iOS project and debug the plugin, you should be receiving the "successfully registering for notifications" log

**Comment by agreensh** [comment]
Thanks...
I was indeed not getting the registered for remote notifications.
Annoyingly, a  clean and rebuild of everything fixed that issue.

However, I'm now never receiving the "CallEvent.answer" event.
Any idea why?

**Comment by diegogarciar** [comment]
The answer event is only received by the callee, not the caller. (with default answer_on_bridge setting)
Is the call actually taking place?

**Comment by agreensh** [comment]
Yes, the call takes place, but neither caller or callee gets the CallEvent.answer event. Both get hangup event.

**Comment by diegogarciar** [comment]
Weird, can you check if you have the same bug running the example project?

**Comment by agreensh** [comment]
So here's a debug log (this is on iOS)

LOG|pushRegistry:didReceiveIncomingPushWithPayload:forType:completion:
flutter: pushRegistry:didReceiveIncomingPushWithPayload:forType:completion:
LOG|callInviteReceived:
flutter: voip-onCallStateChanged CallEvent.log
flutter: callInviteReceived:
Ringing|e613bb99_af6c_4afb_bc63_1909a19c8b92|client:11d3399a_47c1_42c6_ae60_9dcb20f908bf|Incoming
flutter: voip-onCallStateChanged CallEvent.log
flutter: Ringing - From: e613bb99_af6c_4afb_bc63_1909a19c8b92, To: 11d3399a_47c1_42c6_ae60_9dcb20f908bf, Direction: CallDirection.outgoing
flutter: voip-onCallStateChanged CallEvent.ringing
LOG|Incoming call successfully reported.
flutter: Incoming call successfully reported.
flutter: voip-onCallStateChanged CallEvent.log
[connection] nw_endpoint_handler_set_adaptive_read_handler [C5.1 52.21.15.69:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed
[connection] nw_endpoint_handler_set_adaptive_write_handler [C5.1 52.21.15.69:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed
LOG|provider:performAnswerCallAction:
LOG|performAnswerVoiceCall: answering call
flutter: provider:performAnswerCallAction:
flutter: voip-onCallStateChanged CallEvent.log
flutter: performAnswerVoiceCall: answering call
flutter: voip-onCallStateChanged CallEvent.log
flutter: Answer - From: e613bb99_af6c_4afb_bc63_1909a19c8b92, To: 11d3399a_47c1_42c6_ae60_9dcb20f908bf, Direction: CallDirection.incoming
flutter: voip-onCallStateChanged CallEvent.answer
LOG|provider:didActivateAudioSession:
flutter: provider:didActivateAudioSession:
flutter: voip-onCallStateChanged CallEvent.log
flutter: provider:didActivateAudioSession:
flutter: voip-onCallStateChanged CallEvent.log
flutter: CallEvent.log e613bb99_af6c_4afb_bc63_1909a19c8b92
Connected|client:e613bb99_af6c_4afb_bc63_1909a19c8b92|client:11d3399a_47c1_42c6_ae60_9dcb20f908bf|Incoming
LOG|provider:performAnswerVoiceCall() successful
flutter: Connected - From: e613bb99_af6c_4afb_bc63_1909a19c8b92, To: 11d3399a_47c1_42c6_ae60_9dcb20f908bf, StartOn: 2021-06-23 09:39:40.336905, Direction: CallDirection.incoming
flutter: voip-onCallStateChanged CallEvent.connected
flutter: Connected - From: e613bb99_af6c_4afb_bc63_1909a19c8b92, To: 11d3399a_47c1_42c6_ae60_9dcb20f908bf, StartOn: 2021-06-23 09:39:40.337722, Direction: CallDirection.incoming
flutter: voip-onCallStateChanged CallEvent.connected
flutter: provider:performAnswerVoiceCall() successful
flutter: voip-onCallStateChanged CallEvent.log
flutter: provider:performAnswerVoiceCall() successful
flutter: voip-onCallStateChanged CallEvent.log
flutter: ATG in switch:: CallEvent.log call from e613bb99_af6c_4afb_bc63_1909a19c8b92

As you can see, the TwilioVoice reports all the correct stages of the call, but those events are not being received by the running Flutter app while the CallKit UI is active, in the 'switch (event)'. As soon as the call is accepted (and the CallKit ui has gone), then the Flutter app receives the events eg the debug 'flutter: ATG in switch:: CallEvent.log call from e613bb99_af6c_4afb_bc63_1909a19c8b92'

This means there is no way of retrieving the id of the caller until the call is answered.
Is this expected behaviour?

**Comment by agreensh** [comment]
Hi, thanks for your help so far.
I now have iOS working.

On Android, I can make and receive calls, but the identity of the caller is not shown

The Twilio_voice logs show 'null' as the 'to' and 'from'. Is there any extra initialisation that should be done?

I/flutter (18065): Ringing - From: null, To: null, Direction: CallDirection.outgoing
I/flutter (18065): voip-onCallStateChanged CallEvent.ringing
I/flutter (18065): Ringing - From: null, To: null, Direction: CallDirection.outgoing

**Comment by diegogarciar** [comment]
Hi, I think there was an issue for Android that I recently fixed, let me see if I'm missing a commit

**Comment by diegogarciar** [comment]
I have submitted the fix on 0.0.7, if it is still not fixed, check that the posted params on your server are the ones you expect.

**Comment by diegogarciar** [comment]
Closing this for now, if there are any further issues pleas feel free to reopen this or open a new one

**Comment by kaliljoao** [comment]
Hello @agreensh,
I'm currently facing the same issue trying to use CallKit with the plugin. Would you mind explaining how you implemented it in your project to get CallKit working properly?

**Comment by kaliljoao** [comment]
> I can make Twilio calls, but on iOS it is not using CallKit. I notice in the example, a Flutter screen is pushed during calls, but looking at the iOS code (for the plugin) it seems to be integrated with CallKit. Do I have to set any parameters in the code, or add anything to the iOS project (I've already set 'Audio, Airplay, and Picture in Picture' and 'Voice over IP' in the Info.plist).

Hello @agreensh,
I'm currently facing the same issue trying to use CallKit with the plugin. Would you mind explaining how you implemented it in your project to get CallKit working properly?
