### ISSUE TITLE
Bug ios: aborting call before answer will not interrupt it

### ISSUE THREAD

**Issue by eugenioadapta** [cybex-dev/twilio_voice#111]
Steps to reproduce:
Place a call to any number. 
Close the call (hangup) before answer
Issue: under IOS, the call would not be aborted

Expected behavior:
the call should be interrupted

Possible solution:
This line in 
https://github.com/diegogarciar/twilio_voice/blob/master/ios/Classes/SwiftTwilioVoicePlugin.swift
at line 204
`  if (self.call != nil && self.call?.state == .connected) { `
should just become
` if (self.call != nil) { `

Using a fork of this project with the proposed solution fixes the issue

**Comment by cybex-dev** [comment]
I should have such a fix added in my own fork, I'll create a PR to include this if you want me to.

**Comment by eugenioadapta** [comment]
@cybex-dev thanks, but my workaround is stil not tested 100%. Maybe we can experience problems when caller and receiver close the call at the same time? Not sure.
Too bad that this project is abandoned. If you include this fix and publish your package to pub.dev let me know, we will include it in our app

**Comment by cybex-dev** [comment]
> @cybex-dev thanks, but my workaround is stil not tested 100%. Maybe we can experience problems when caller and receiver close the call at the same time? Not sure. Too bad that this project is abandoned. If you include this fix and publish your package to pub.dev let me know, we will include it in our app

Sounds good - got a bunch of fixes, additions, feature updates, etc that I need to add - just haven't had the time.

I'll check in sometime in the next week or so.

**Comment by cybex-dev** [comment]
@eugenioadapta seems you aren't the only one to experience this issue.

I'm upgrading this library atm, will add this fix you suggested.

**Comment by cybex-dev** [comment]
@eugenioadapta I'll be reviewing this suggestion later today.

**Comment by yacoublambaz** [comment]
Any updates here? I'm facing the same issue.

**Comment by cybex-dev** [comment]
Hi @yacoublambaz - I'm actively making upgrades this week to merge new features, platform support, fixes, etc.

**Comment by yacoublambaz** [comment]
@cybex-dev I appreciate your efforts! To confirm, should I expect this bug to be fixed with your upgrades?

**Comment by cybex-dev** [comment]
I've yet to review all PRs and address all outstanding bugs/issues, though I will make a pre-release available for testing prior to pub.dev release (by @diegogarciar)

**Comment by cybex-dev** [comment]
> Steps to reproduce: Place a call to any number. Close the call (hangup) before answer Issue: under IOS, the call would not be aborted
> 
> Expected behavior: the call should be interrupted
> 
> Possible solution: This line in https://github.com/diegogarciar/twilio_voice/blob/master/ios/Classes/SwiftTwilioVoicePlugin.swift at line 204 ` if (self.call != nil && self.call?.state == .connected) {` should just become `if (self.call != nil) {`
> 
> Using a fork of this project with the proposed solution fixes the issue

Great suggestion, expect it in this upcoming release - if you like to test this early in this package, I'll be make a pre-release branch available before it goes live.

**Comment by cybex-dev** [comment]
Available in next release, closing.
