### ISSUE TITLE
Keep getting Invalid Token

### ISSUE THREAD

**Issue by arvie9** [cybex-dev/twilio_voice#117]
I'm getting access token from my server successfully. I verify this by using it with Twilio's example iOS project and it successfully makes a call. However on Flutter, it just keeps saying the token is invalid. Any clue? Or is this package not functional anymore?

<img width="933" alt="230459782-37e022de-cce4-4377-a7cf-bb3bd0ce9f3d" src="https://user-images.githubusercontent.com/56938851/230511438-15c0d220-1397-4c0a-b335-ed00f42a1c05.png">

**Comment by cybex-dev** [comment]
Hi @arvie9,
If you haven't, please review these https://www.twilio.com/docs/api/errors/20107. 

What caught my attention is:
- Invalid Access Token Signature,  and 
- Forbidden:403 
both which do not seem normal. 

I'd recommend:
- reviewing your **generate token** function including environment variables (i.e. account sid, app sid, etc) as this might generate an invalid/incorrect token.
- Further, possibly compare your **generate token** function to that provide in Twilio's quick starters as a starting point for debugging.

Also, this might be helpful: https://support.twilio.com/hc/en-us/articles/115015890207-Troubleshooting-Invalid-Access-Tokens

**Comment by arvie9** [comment]
The token seems fine. I even tried hard coding a valid signature token from jwt.io and still got the same issue... 


<img width="1205" alt="Screen Shot 2023-04-06 at 4 13 17 PM" src="https://user-images.githubusercontent.com/56938851/230510704-e35aa02b-7627-47ca-a128-7c7493848166.png">
<img width="973" alt="Screen Shot 2023-04-06 at 4 11 52 PM" src="https://user-images.githubusercontent.com/56938851/230510706-665154fe-6ac6-444e-9dd3-d5cbfc9c2151.png">

**Comment by arvie9** [comment]
Also, is this normal? When I do 'pod install' it says twilio_voice is version **0.0.1** but labeled **0.0.9** on pub.dev.
<img width="311" alt="Screen Shot 2023-04-06 at 4 43 42 PM" src="https://user-images.githubusercontent.com/56938851/230513278-e1fec02c-87e1-4506-87b8-8a36da98260f.png">

**Comment by cybex-dev** [comment]
@arvie9 check this out - might be helpful.
https://stackoverflow.com/questions/52410506/twilio-invalid-access-token-signature-ios-swift
