### ISSUE TITLE
Mic is not working when phone is locked and app running foreground 

### ISSUE THREAD

**Issue by kashiftariq1997** [cybex-dev/twilio_voice#118]
Mic is not working when the phone is locked and the app is running foreground

**Comment by cybex-dev** [comment]
Hi @kashiftariq1997 
Could you provide some information, state wise, etc.
Does your app have mic permissions, which platform, etc?

**Comment by kashiftariq1997** [comment]
@cybex-dev It starts working I'm closing this issue. and I'm getting another issue ON IOS Device I will create new Issue for that

**Comment by kashiftariq1997** [comment]
@cybex-dev please check this issue https://github.com/diegogarciar/twilio_voice/issues/119
