### ISSUE TITLE
"Duplicate plugin key: twilio_voice"

### ISSUE THREAD

**Issue by kashiftariq1997** [cybex-dev/twilio_voice#119]
When an App runs on an IOS device app suddenly crashes but  when I remove Twilio from the app it's worked fine 
<img width="1439" alt="Screenshot 2023-04-10 at 10 06 41 PM" src="https://user-images.githubusercontent.com/47936915/230954434-5fbad531-cde8-44d6-9a57-2430b8968931.png">

**Comment by kashiftariq1997** [comment]
<img width="706" alt="Screenshot 2023-04-10 at 10 22 20 PM" src="https://user-images.githubusercontent.com/47936915/230955865-08ab2093-df56-49bb-9905-9337e3ed097e.png">

**Comment by kashiftariq1997** [comment]
<img width="628" alt="Screenshot 2023-04-10 at 11 11 31 PM" src="https://user-images.githubusercontent.com/47936915/230966330-5d32e216-fd2f-4fce-b1aa-bb9e409b914c.png">
When I comment on these Highlight lines It will work fine. Here I pass the empty function onStart in IOS configrations

**Comment by cybex-dev** [comment]
> <img alt="Screenshot 2023-04-10 at 11 11 31 PM" width="628" src="https://user-images.githubusercontent.com/47936915/230966330-5d32e216-fd2f-4fce-b1aa-bb9e409b914c.png">
> 
> When I comment on these Highlight lines It will work fine. Here I pass the empty function onStart in IOS configrations

Hi @kashiftariq1997, what am I looking at here? What is this `onStart` function. It seems to be related to a notification plugin?

Re: duplicate plugin issue - see if any of these helps:
 - https://stackoverflow.com/questions/55950241/duplicate-plugin-key-fltgooglemapsplugin
 - https://github.com/flutter/flutter/issues/113619
 - https://github.com/fluttercommunity/flutter_downloader/issues/154

**Comment by kashiftariq1997** [comment]
<img width="324" alt="Screenshot 2023-04-11 at 4 45 06 AM" src="https://user-images.githubusercontent.com/47936915/231020073-bcbe3aaf-7f88-4022-bfdf-e3d715f94b61.png">
<img width="329" alt="Screenshot 2023-04-11 at 4 47 17 AM" src="https://user-images.githubusercontent.com/47936915/231020294-579003d6-369f-4a2a-9c83-4f0d6d2f3f83.png">

When trying to install pods it installs two TwillioVoice Pods

**Comment by kashiftariq1997** [comment]
@cybex-dev, when I comment on this highlighted code from the package app, stops crashing but the Twilio call is not working 
<img width="676" alt="Screenshot 2023-04-11 at 7 52 15 PM" src="https://user-images.githubusercontent.com/47936915/231220301-9ea4fcde-6bda-4557-baf0-92a86883f0d4.png">

**Comment by kashiftariq1997** [comment]
@cybex-dev any solution for that?

**Comment by diegogarciar** [comment]
> When trying to install pods it installs two TwillioVoice Pods
This is perfectly normal, you can see that one is lowercase and one is uppercase, one is the native pod and the other one is the plugin

**Comment by diegogarciar** [comment]
> @cybex-dev, when I comment on this highlighted code from the package app, stops crashing but the Twilio call is not working

are you sure you're not calling this code twice?

**Comment by kashiftariq1997** [comment]
@diegogarciar Yes I'm sure.

**Comment by kashiftariq1997** [comment]
@diegogarciar and it's working fine when I comment the background service code

**Comment by kashiftariq1997** [comment]
@diegogarciar is there anything common in these packages twilio_voice and flutter_background_services

**Comment by cybex-dev** [comment]
> @cybex-dev any solution for that?

I'll check out this problem today, commenting out plugin registrar or message channels would prevent proper operation of the plugin i.e. you won't receive any events because the plugin wasn't loaded.

On which devices are you experiencing this?
Can you problem a rough MCVE for this issue? pubspec.yaml, `main.dart`. 
Does the provided example work for you?

Running a `pod install` should install the latest `TwilioVoice` (SDK, 6.3.1) and `twilio_voice` (this library, 0.0.1).

**Comment by cybex-dev** [comment]
> 

Yes, this is expected and normal.

Running a `pod install` should install the latest `TwilioVoice` (SDK, 6.3.1) and `twilio_voice` (this library, 0.0.1).

**Comment by kashiftariq1997** [comment]
On which devices are you experiencing this?
I'm running this on apple iphone 7 plus

**Comment by kashiftariq1997** [comment]
NO provided example not work for me

**Comment by cybex-dev** [comment]
> On which devices are you experiencing this? I'm running this on apple iphone 7 plus

I'm not running any emulator - this is done in you terminal/command-line.

cd `path_to_twilio_voice/example/ios`
Remove Pods `rm -r Pods`
Remove lock file `rm Podfile.lock`
Install pods `pod install`

then run.

**Comment by cybex-dev** [comment]
> NO provided example not work for me

1. Please clear your XCode build cache (and your current IDE cache). 
2. Add a valid `GoogleService-Info.plist` file to the example project, rename your project to the same org/domain name and try running the example again.

**Comment by kashiftariq1997** [comment]
> path_to_twilio_voice/example/ios

@diegogarciar  I tried this

**Comment by kashiftariq1997** [comment]
I'm using the flutter_background_service package and this package reruns the app I think for the foreground.

**Comment by kashiftariq1997** [comment]
@diegogarciar 
`let registrar = controller.registrar(forPlugin: "twilio_voice")
        if let unwrappedRegistrar = registrar {
            let eventChannel = FlutterEventChannel(name: "twilio_voice/events", binaryMessenger: unwrappedRegistrar.messenger())
            eventChannel.setStreamHandler(self)
        }`
     is there anyother way to in which we don't register twilio_voice here 
        `let registrar = controller.registrar(forPlugin: "twilio_voice")`

**Comment by cybex-dev** [comment]
Hi @kashiftariq1997, did you end up resolving this issue?

**Comment by kashiftariq1997** [comment]
I just add the native code in the app and I Deleat the IOS from the package

**Comment by cybex-dev** [comment]
Hmm, thanks for letting me know - I'll investigate further over the weekend/next week.

**Comment by cybex-dev** [comment]
@kashiftariq1997 I was unable to replicate this issue - I'll be closing for now.

**Comment by piyushyadav4904** [comment]
getting same issue @cybex-dev

**Comment by piyushyadav4904** [comment]
![Screenshot 2024-01-18 at 6 07 12 a m](https://github.com/cybex-dev/twilio_voice/assets/70249279/13ad9ba2-495c-482d-9754-2749e20eaf86)
/
why it install the TwilioVoice two times ?

**Comment by marijam26** [comment]
Same issue `Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Duplicate plugin key: twilio_voice'`

**Comment by stanojevicboban** [comment]
To circumvent this, I've forked to project and updated SwiftTwilioVoicePlugin.swift so it checks if the plugin is already registered:

```
if !controller.hasPlugin("twilio_voice") {
    let registrar = controller.registrar(forPlugin: "twilio_voice")
    if let unwrappedRegistrar = registrar {
        let eventChannel = FlutterEventChannel(name: "twilio_voice/events", binaryMessenger: unwrappedRegistrar.messenger())
        eventChannel.setStreamHandler(self)
    }
}
```

**Comment by cybex-dev** [comment]
#222
