### ISSUE TITLE
Release Build fails with splash_icon on drawable folder

### ISSUE THREAD

**Issue by arvie9** [cybex-dev/twilio_voice#120]
Everything seems fine and working when I run on the Simulator. But when I make an APK, it fails to build.
I have the splash_icon.png on the drawable and mipmap folders but still run into this error during build.

`Execution failed for task ':twilio_voice:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     /Users/arvie/flutter/.pub-cache/git/twilio-c2a2325092c7f9a16347d4b17af0be9b3477ce92/android/src/main/res/layout/activity_answer.xml:17: AAPT: error: resource drawable/splash_icon (aka com.twilio.twilio_voice:drawable/splash_icon) not found.

     /Users/arvie/flutter/.pub-cache/git/twilio-c2a2325092c7f9a16347d4b17af0be9b3477ce92/android/src/main/res/layout/activity_background_call.xml:18: AAPT: error: resource drawable/splash_icon (aka com.twilio.twilio_voice:drawable/splash_icon) not found.`

<img width="269" alt="Screen Shot 2023-04-13 at 12 52 21 AM" src="https://user-images.githubusercontent.com/56938851/231691875-ac66ae78-f31f-4d36-a86c-1ca38d0a1fd5.png">

**Comment by diegogarciar** [comment]
remove it from the drawable folder, do you also have drawable-xxxhdpi?

**Comment by arvie9** [comment]
> 

Actually, what worked for me is I followed the xml path in pub cache:
`/Users/arvie/flutter/.pub-cache/git/twilio-c2a2325092c7f9a16347d4b17af0be9b3477ce92/android/src/main/res/layout/activity_background_call.xml:`

and put the PNG on the drawable folder there and it worked. 🤷🏽‍♂️

**Comment by cybex-dev** [comment]
@arvie9 out of interest sake, did you try clearing caches (in AS or VSCode equivalent) & flutter clean?

**Comment by arvie9** [comment]
> @arvie9 out of interest sake, did you try clearing caches (in AS or VSCode equivalent) & flutter clean?

Yes, multiple times, but to no avail.

**Comment by cybex-dev** [comment]
Hi @arvie9, did you manage to resolve this issue?

**Comment by Ahmadgnoor** [comment]
@cybex-dev  just put the splash_Icon.png  image of flutter icon or any image an pull it to master repo.... it solve the issue

**Comment by Ahmadgnoor** [comment]
i have clone the plugin and on run same issue but after addiing a png file to drawable solve the issue

**Comment by cybex-dev** [comment]
Wonderful, I'll look into making this process simpler in future. Closing.
