### ISSUE TITLE
this plugin not working i tested it on andriod device 

### ISSUE THREAD

**Issue by vikasyiweb** [cybex-dev/twilio_voice#121]
when i make a call than my makeCall API working on the server(i checked on server logs) but i don't receive call on my Device Please help  me

**Comment by tanmoy27112000** [comment]
same is happening for me. not able to receive calls but can make call. @diegog-sf

**Comment by tanmoy27112000** [comment]
`Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.`

**Comment by Erchil66** [comment]
@vikasyiweb try to fork at @cybex-dev twilio on this and search for latest braanch for android and i do recommend follow the steps they gave and do it again, This package it not getting updated so far or not yet, So for the mean time do forking for now and tweak some codes on native android and ios using swift. For your own needs.

**Comment by cybex-dev** [comment]
> @vikasyiweb try to fork at @cybex-dev twilio on this and search for latest braanch for android and i do recommend follow the steps they gave and do it again, This package it not getting updated so far or not yet, So for the mean time do forking for now and tweak some codes on native android and ios using swift. For your own needs.

I know @diegogarciar is a bit busy, I'm doing some maintenance on this package atm i.e. adding web support. I'll be updating with Android & iOS fixes during this upcoming week.

If you urgently need a fix, feel free to clone my fork but I'd advise waiting for updates here.

**Comment by tanmoy27112000** [comment]
I have fixed it. I will make a PR for the fix.

**Comment by cybex-dev** [comment]
> `Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.`

this has been merged in #116, it's currently available in `master` and will be made available in the next release.

**Comment by cybex-dev** [comment]
> I have fixed it. I will make a PR for the fix.

Please review your PR, fetch, merge changes and push updates.

**Comment by cybex-dev** [comment]
Closing in favour of PR #122
