### ISSUE TITLE
[IOS] Call ends as soon as a number is dialed

### ISSUE THREAD

**Issue by soapthepro** [cybex-dev/twilio_voice#123]
I have successfully installed this plugin for my IOS app and its all stable and everything gets registered. I receive the logs too "registered for push notifications" but as soon as I call to any number it takes me to call screen and within few seconds it takes me back to my home screen. The logs that are like calling from nil to nil and then a couple for callevent logs saying call started and then more callevent logs of call ended. Let me know if there is any fix to this. I'm using the latest version of XCODE and testing it on lastest IOS.

**Comment by alzihadi** [comment]
@soapthepro Seems like you are using a simulator. To make an outbound call, you need to run app on a physical device.

**Comment by soapthepro** [comment]
@alzihadi Yeah, I figured it out later that day. Thanks!
