### ISSUE TITLE
CallDirection of Active Call is always CallDirection.outgoing.

### ISSUE THREAD

**Issue by agent515** [cybex-dev/twilio_voice#130]
On Callee Side.

Expected:
`Ringing - From: Alice, To: Bob, Direction: CallDirection.incoming`

Actual:
`Ringing - From: Alice, To: Bob, Direction: CallDirection.outgoing`

**Comment by cybex-dev** [comment]
@agent515 many thanks for the PR - will review and merge later today.

**Comment by cybex-dev** [comment]
See [release 0.1.0](https://pub.dev/packages/twilio_voice/versions/0.1.0)
