### ISSUE TITLE
Background call UI stays even after the call is disconnected

### ISSUE THREAD

**Issue by tanmoy27112000** [cybex-dev/twilio_voice#133]
When the app is closed and a call comes in android. the pickup and decline ui shows up. if the call is connected or declined. The first UI stays persistant and can be seen in the recent apps. 
![WhatsApp Image 2023-06-28 at 11 50 49 AM](https://github.com/diegogarciar/twilio_voice/assets/22212661/d8ba8904-86bd-4cb3-a66a-c795db4228a2)

**Comment by cybex-dev** [comment]
Hi @tanmoy27112000.

I'm moving away from custom call screen and using the native `ConnectionService` (i.e. CallKit). If you need a fix asap, let me know.

**Comment by cybex-dev** [comment]
Check out #151 merged

**Comment by cybex-dev** [comment]
See [release 0.1.0](https://pub.dev/packages/twilio_voice/versions/0.1.0)
