### ISSUE TITLE
A lot of issues in my project I need to discuss/address

### ISSUE THREAD

**Issue by kdokhanx98** [cybex-dev/twilio_voice#135]
so I am building a Flutter project & integrating this library.
Already everything is fine, call is placed and listening  to events but I noticed that decline event doesn't exist on CallEvents class.
Also I am facing issue where I can't listen to errors in general or connectionError.
<img width="295" alt="image" src="https://github.com/diegogarciar/twilio_voice/assets/76620656/82fa4f60-303b-46f3-84d3-2f8344388614">

**Comment by kdokhanx98** [comment]
Can't listen to such errors.
<img width="453" alt="Screenshot 2023-07-05 at 2 52 05 PM" src="https://github.com/diegogarciar/twilio_voice/assets/76620656/bd5f8c5b-153a-4301-badf-0946d7898302">

**Comment by cybex-dev** [comment]
Hi @kdokhanx98 

See [CallEvent](https://github.com/diegogarciar/twilio_voice/blob/master/lib/models/call_event.dart#L14) `decline`.

Let me know if you'd like to see the associated code too.

**Comment by kdokhanx98** [comment]
Hi again @cybex-dev, Thank you so much for helping, but now I noticed I face an instant crash when I try to place calls on release mode for android devices only, Did you face such thing? how to solve it please? Thank you so much

**Comment by cybex-dev** [comment]
> Hi again @cybex-dev, Thank you so much for helping, but now I noticed I face an instant crash when I try to place calls on release mode for android devices only, Did you face such thing? how to solve it please? Thank you so much

Hmm, would you mind opening up a new issue for this please? Including steps to reproduce (i.e. when/how it happens).

**Comment by cybex-dev** [comment]
See [release 0.1.0](https://pub.dev/packages/twilio_voice/versions/0.1.0)
