### ISSUE TITLE
Question: Getting custom parameters?

### ISSUE THREAD

**Issue by KPR7168** [cybex-dev/twilio_voice#14]
Hi there,

Really love the simplicity of integration. I manage to get the call on both platforms but cannot find a way to get custom parameters from `Call` or `ActiveCall` like we can do with [native api](https://twilio.github.io/twilio-voice-ios/docs/latest/Classes/TVOCallInvite.html#//api/name/customParameters). Any suggestion would be grateful.

Thanks 🙏🏻

**Comment by diegogarciar** [comment]
Actually this is not yet implemented this could be a good feature request. If you already know how to do it please go ahead and submit a pull request. Otherwise any example of how you do it natively would help me a lot to develop the feature.

**Comment by KPR7168** [comment]
Have a [pull request](https://github.com/diegogarciar/twilio_voice/pull/15) for this.
