### ISSUE TITLE
Call Configuration : Not a bug, call not placing

### ISSUE THREAD

**Issue by muzammil-git** [cybex-dev/twilio_voice#149]
When I use the function below it place the call and says "Congratulations! You have made your first call! Good bye."
Why isn't it calling on the given number. 

Am I missing some parameter ?

TwilioVoice.instance.call.place(
    to: "+92xxxxxxxxxx",
    from: "+1xxxxxxxxxxxx",
    extraOptions: {},
 );

**Comment by cybex-dev** [comment]
@muzammil-git this is not a bug with Twilio Voice but a change required in your TwiML app.

https://github.com/twilio/voice-quickstart-objc/issues/103

**Comment by muzammil-git** [comment]
I noticed the "to" parameter is not received by make-call function on twilio service, I have deployed twilio serverless.

It should trigger the length is 1, but its not receiving"to"

TwilioVoice.instance.call.place(
                    to: "1",
                    from: "client:alice",
                    extraOptions: {},
);

**Comment by muzammil-git** [comment]
Reference
![image](https://github.com/diegogarciar/twilio_voice/assets/54685589/b890aed7-0985-4817-a0c7-a7847c76ea97)

**Comment by cybex-dev** [comment]
> Reference ![image](https://user-images.githubusercontent.com/54685589/258785646-b890aed7-0985-4817-a0c7-a7847c76ea97.png)

Ah, I see the confusion.

Review the `context`/`event` to see your incoming parameters. The [Twilio Voice Android quickstart](https://github.com/twilio/voice-quickstart-android/blob/master/app/src/main/java/com/twilio/voice/quickstart/VoiceActivity.java#L459) adds this field to the call parameters as `to`, while the original developer for `twilio_voice` [changed this](https://github.com/diegogarciar/twilio_voice/blob/master/lib/_internal/method_channel/twilio_call_method_channel.dart#L31) to `To`.

I will need to address this in future.

**Recommendation**
For now, make use of `event.From` or `event.To` as suggested in the [README.md](https://github.com/diegogarciar/twilio_voice/blob/master/README.md#setting-up-the-application) e.g.
```js
    let to = event.to;
    if(isEmptyOrNull(to)) {
        to = event.To;
        if(isEmptyOrNull(to)) {
            console.error("Could not find someone to call");
            to = undefined;
        }
    }
```

In future, I'll revert these parameters back to the original `to` and `from`.

**Comment by muzammil-git** [comment]
Great that works, thanks @cybex-dev

**Comment by cybex-dev** [comment]
Glad to hear it.
