### ISSUE TITLE
Need help : Can't get incoming call notification.

### ISSUE THREAD

**Issue by muzammil-git** [cybex-dev/twilio_voice#150]
This is how my AndroidManifest,xml looks, can you please help on how I can get incoming call notification, there's not much documentation I found to solve this. 

![image](https://github.com/diegogarciar/twilio_voice/assets/54685589/6c5d7f56-15a4-4b04-88a9-0fa50b322bb6)

**Comment by cybex-dev** [comment]
> This is how my AndroidManifest,xml looks, can you please help on how I can get incoming call notification, there's not much documentation I found to solve this.
> 
> ![image](https://user-images.githubusercontent.com/54685589/259098162-6c5d7f56-15a4-4b04-88a9-0fa50b322bb6.png)

Could you clarify what you mean with:
> how I can get incoming call notification

What is the use-case you have in mind?

**Comment by muzammil-git** [comment]
I am calling to my twilio number and upon calling I should have a notification like incoming call from xyz.

**Comment by muzammil-git** [comment]
Just like this.
![image](https://github.com/diegogarciar/twilio_voice/assets/54685589/29676fab-1808-4bb5-81aa-84cd63ee121d)

**Comment by cybex-dev** [comment]
> I am calling to my twilio number and upon calling I should have a notification like incoming call from xyz.

I'm sure the [example](https://github.com/diegogarciar/twilio_voice/blob/master/example/lib/main.dart#L217) has this functionality?

Let me know if it doesn't work for you.

**Comment by muzammil-git** [comment]
I tried but, it doesn't work for me.

**Comment by muzammil-git** [comment]
The incoming call only applies to web i.e written
SS for reference.

![image](https://github.com/diegogarciar/twilio_voice/assets/54685589/ce8789ee-f981-4390-ae94-99b4d7bb48a0)

**Comment by cybex-dev** [comment]
In that case, I'd recommend using the `CallEvent.ringing`, this should suffice for all platforms. The `CallEvent.incoming` is used with Twilio Voice Web SDKs in lieu of the `ringing`, since Web (or all Mac platforms) don't provide a native callkit.

**Comment by muzammil-git** [comment]
Okay got the point, but my event Callevent.ringing is not working either. When I call from another phone to my twilio number it doesn't get the notification.

I have tested sending notification from https://testfcm.com/ , I am getting the below error. Am I missing something.

E/FlutterFcmService(13829): The message was not a valid Twilio Voice SDK payload:

**Comment by muzammil-git** [comment]
My payload looks like this, is this the way ?

{
  "type": "incoming_call",
  "to": "+14155555555",
  "sid": "",
  "status": "ringing",
  "direction": "inbound",
  "duration": 0
}

**Comment by cybex-dev** [comment]
@muzammil-git I'd advise you test out the example app, review the ReadMe, this should get you up to speed somewhat faster and give you much more insight.
