### ISSUE TITLE
Got error userId not set and access_token null

### ISSUE THREAD

**Issue by kennzy1000** [cybex-dev/twilio_voice#16]
Hello, 

When I make a call, I received the log error  userId not set and access token can not be null, and display stood at connecting.

**Comment by diegogarciar** [comment]
have you provided your accessToken when performing the call or prior to it?
https://github.com/diegogarciar/twilio_voice#setting-the-tokens

**Comment by kennzy1000** [comment]
I was able to bypass this error. However, I noticed the token expires.

**Comment by cybex-dev** [comment]
> I was able to bypass this error. However, I noticed the token expires.

From the caller's side, you need to check if the token will expire (according to Twilio, the token expiring event will fire 3 minutes prior to token expiring). As the caller, you need to verify your token hasn't expired or will expire soon prior to making a call.

**Comment by cybex-dev** [comment]
Closing due to lack of feedback.
