### ISSUE TITLE
Integrate IOS call with OS

### ISSUE THREAD

**Issue by ardeshir-33033** [cybex-dev/twilio_voice#175]
I use the updated version of twilio voice and on android the package have been integrated fully with OS phone call but it seems that is not the case for IOS. 
does twill voice package support this? if yes how can I use it ?

**Comment by cybex-dev** [comment]
Hi @ardeshir-33033 

Yes, Android has recently been fully integrated with as a system-managed call. iOS offers no other option than system integrated. Could you advise why it doesn't seem to be the case?

As reference, see [iOS Features](https://github.com/cybex-dev/twilio_voice#features) and [iOS setup](https://github.com/cybex-dev/twilio_voice#ios-setup).

**Comment by cybex-dev** [comment]
Hi @ardeshir-33033, 

Following up on my previous suggestion, were you successful in resolving your issue(s)?
