### ISSUE TITLE
IOS won't receive phone calls

### ISSUE THREAD

**Issue by ardeshir-33033** [cybex-dev/twilio_voice#176]
I have followed the path for the package instruction for Android and in Android I get calls and everything is fine.
but in IOS instruction there is nothing special on the documentation and my app won't receive calls.
But twill voice instance says that the phone is registered though. can you hint me where the problem might be?

**Comment by cybex-dev** [comment]
iOS does not require any special setup requirements by the package itself other than mic access & push notification support. In debugging why iOS does not receive calls, there can be several issues. 

## Device checklist:
 - Do you have push notification access?
 - Did you successfully register your device with Twilio Voice?
 - Is the Twilio AuthToken expired/invalid?
 - Are you calling / receiving calls to/from the correct client Id
 - (iOS specific) Are you using the correct APNS credentials when generating your token? (Sandbox/Production, see [iOS Push Credentials](https://github.com/cybex-dev/twilio_voice#ios-1))

## Backend checklist:
- Did you generate a voice grant token?
- Did you correctly assign the client Id?
- Does Twilio Logs report an error delivering call (see Twilio error logs)

This is not extensive, but a start.

**Comment by cybex-dev** [comment]
@ardeshir-33033 (updated, check your credentials token, might be the problem)

**Comment by cybex-dev** [comment]
Hi @ardeshir-33033, any luck?

**Comment by ardeshir-33033** [comment]
Hi @cybex-dev Sorry for the late response,
yes great checklist by the way, the problem were in the IOS push credentials Sandbox and production mode.

**Comment by cybex-dev** [comment]
Wonderful, I'll close up the issue.

I'll make an FAQ section too to address these types of issues, thanks for the (suggestion).
