### ISSUE TITLE
Error outputting keys and certificates

### ISSUE THREAD

**Issue by yazanturk** [cybex-dev/twilio_voice#178]
create a certification on Apple developer (VoIP Services) and export as certification.p12 when executing the code 
openssl pkcs12 -in certification.p12 -nokeys -out sandbox_cert.pem -nodes

this is the output 
Error outputting keys and certificates
00530DDF01000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:341:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()

I am using a MacBook pro

**Comment by cybex-dev** [comment]
This isn't a Flutter `twilio_voice` issue, but I'll try to assist where I can

Have you seen [this](https://github.com/aws-amplify/amplify-cli/issues/12969#issuecomment-1642458812)?

**Comment by yazanturk** [comment]
@cybex-dev  Thank you It Work

**Comment by cybex-dev** [comment]
Wonderful, I close the ticket.
