### ISSUE TITLE
 Android resource linking failed

### ISSUE THREAD

**Issue by cuongloveit** [cybex-dev/twilio_voice#18]
I have put splash_icon to drawable but errror still happens :(
* What went wrong:                                                      
Execution failed for task ':twilio_voice:verifyReleaseResources'.       
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed                                    
     ERROR:/Users/apple/.pub-cache/hosted/pub.dartlang.org/twilio_voice-0.0.9/android/src/main/res/layout/activity_answer.xml:31: AAPT: error: resource drawable/splash_icon (aka com.twilio.twilio_voice:drawable/splash_icon) not found.
                                                                        
     ERROR:/Users/apple/.pub-cache/hosted/pub.dartlang.org/twilio_voice-0.0.9/android/src/main/res/layout/activity_background_call.xml:32: AAPT: error: resource drawable/splash_icon (aka com.twilio.twilio_voice:drawable/splash_icon) not found.

**Comment by diegogarciar** [comment]
Can you show me an image of the folder tree with the file?

**Comment by EngYasmeenMahmoud** [comment]
i solve this issue by creating new repsitory  and add splash_icon to drawable folder and import twilio voice n my application as this  
twilio_voice:
    git:
      url: https://github.com/EngYasmeenMahmoud/twilio.git
      ref: master
