### ISSUE TITLE
Question: When app terminate (Close) the incoming call can't showing  userid and avatar?

### ISSUE THREAD

**Issue by thangtq3ttech** [cybex-dev/twilio_voice#19]
Question: When app terminate (Close) the incoming call can't showing  user id and avatar? 
https://drive.google.com/file/d/1HiL9xHOggOyRvoAJY-QVAlAarZ-7VtRF/view?usp=sharing

Thanks

**Comment by diegogarciar** [comment]
Not currently, you would need to customize the android code to do it.

**Comment by CricIT** [comment]
Facing same issue, is there any alternative solution?

**Comment by cybex-dev** [comment]
> Question: When app terminate (Close) the incoming call can't showing user id and avatar? https://drive.google.com/file/d/1HiL9xHOggOyRvoAJY-QVAlAarZ-7VtRF/view?usp=sharing
> 
> Thanks

See https://github.com/diegogarciar/twilio_voice/issues/51#issuecomment-962003085

**Comment by cybex-dev** [comment]
Feature in development, will be released on next update

See [#51 (comment)](https://github.com/diegogarciar/twilio_voice/issues/51#issuecomment-1563757890)

**Comment by cybex-dev** [comment]
Check out #151 merged

**Comment by cybex-dev** [comment]
See [release 0.1.0](https://pub.dev/packages/twilio_voice/versions/0.1.0)
