### ISSUE TITLE
How can i change the name from notification and the native android call and ios callKit.

### ISSUE THREAD

**Issue by Erchil66** [cybex-dev/twilio_voice#192]
@cybex-dev  @diegogarciar 
Really fantastic about the new update. Also able receive calls and do outgoing call for android/IOS.

My Question is how can i change the incoming call names from native ui's 
? Also from FCM, The problem am having is that my from data is a number not a name, It was put on the custom parameters. I would like some help where i can change it in the package. Is this possible?

**Comment by cybex-dev** [comment]
Hi @Erchil66,

I'm very happy you like the new Android update.

Would you care to provide more information as to your requirements please, to give me a better understanding of your desired end result.

For now, I've implemented functionality that uses a waterfall type approach in resolving the name for the notification, please review [interpretting-parameteres](https://github.com/cybex-dev/twilio_voice#interpreting-parameters) and the explanation section aswel. 

Maybe this will give you a starting point.

**Comment by Erchil66** [comment]
Hi @cybex-dev , 

From images example below the sample for notification answer and cancel, But the above text from **Incoming call via** is a number for me in from, Would like to change that in the package if possible same on the native call ui in android. And can't change it either in laravel since it will affect in other things and quite complicated.



Note: am using emulator to receive calls and it's working.

![Screenshot_1699503217](https://github.com/cybex-dev/twilio_voice/assets/92772509/91bab46a-152c-42bb-9cf5-8648867b31e2)
![Screenshot_1699503234](https://github.com/cybex-dev/twilio_voice/assets/92772509/bb4f7d1d-0056-4cfa-ad52-ab378035736b)

**Comment by Erchil66** [comment]
> Hi @Erchil66,
> 
> I'm very happy you like the new Android update.
> 
> Would you care to provide more information as to your requirements please, to give me a better understanding of your desired end result.
> 
> For now, I've implemented functionality that uses a waterfall type approach in resolving the name for the notification, please review [interpretting-parameteres](https://github.com/cybex-dev/twilio_voice#interpreting-parameters) and the explanation section aswel.
> 
> Maybe this will give you a starting point.

Forgot to reply on this, Okay will try to understand the flow first and do somw changes thanks for this. Also Slr.

**Comment by cybex-dev** [comment]
> Hi @cybex-dev ,
> 
> From images example below the sample for notification answer and cancel, But the above text from **Incoming call via** is a number for me in from, Would like to change that in the package if possible same on the native call ui in android. And can't change it either in laravel since it will affect in other things and quite complicated.
> 
> Note: am using emulator to receive calls and it's working.
> 
> ![Screenshot_1699503217](https://user-images.githubusercontent.com/92772509/281615089-91bab46a-152c-42bb-9cf5-8648867b31e2.png) ![Screenshot_1699503234](https://user-images.githubusercontent.com/92772509/281615093-bb4f7d1d-0056-4cfa-ad52-ab378035736b.png)

Hi @Erchil66,

Yes, this is definately possible and the package already integrates this functionality.

**- Android:**
Discussed in [Incoming Calls](https://github.com/cybex-dev/twilio_voice/blob/master/README.md#incoming-calls) and [Outgoing Calls](https://github.com/cybex-dev/twilio_voice/blob/master/README.md#outgoing-calls).

**- iOS**
Not present yet, this feature is pending in addition to code refactor & rework, I'll be including these changes in the next release (bar any hotfixes)

_Note: Some Android devices allow for setting a call subject (possibly a business name) e.g. Google Pixel supports this capability where as Samsung (atleast on my test devices) did not._

Thanks for bringing attention to this feature, I'll revise documentation to allow for a better at-a-glance idea on how to use this functionality.

**Comment by cybex-dev** [comment]
#187

**Comment by cybex-dev** [comment]
@Erchil66 were you successful in name changing, etc?

**Comment by Erchil66** [comment]
@cybex-dev Yes, i did change some of it sometimes it work, Sometimes not when app is terminate, Still looking for a way, 

It would be good also when receiving we should also indicate or which data we pull to show name if i able to successfully do it will give a pr it might be helpful to someone just incase.

Will close this now. Again thanks @cybex-dev

**Comment by bazl-E** [comment]
@Erchil66 is there any way to show at least an incoming call number in iOS?
