### ISSUE TITLE
[ANDROID] After `TwilioVoice.instance.unregister();` still receiving calls

### ISSUE THREAD

**Issue by tanmoy27112000** [cybex-dev/twilio_voice#195]
### Issue Summary
During logout i am using the unregister command , still receiving call for that account.

### Steps to Reproduce

1.  register for calling
2. logout and unregister
3. check for incoming call

**Comment by cybex-dev** [comment]
Hi @tanmoy27112000,

Which platform are you using?

**Comment by tanmoy27112000** [comment]
Android

**Comment by cybex-dev** [comment]
@tanmoy27112000 thank you for pointing this issue out - I've confirmed it is a major bug and will put out a hotfix asap.

**Comment by cybex-dev** [comment]
@tanmoy27112000 fix has been added, I'll tag you when hotfix has been released to pub.dev.

**Comment by cybex-dev** [comment]
https://github.com/cybex-dev/twilio_voice/releases/tag/0.1.3

**Comment by cybex-dev** [comment]
Released 0.1.3 to pub.dev
