### ISSUE TITLE
Questions: how do I call a URL from my server

### ISSUE THREAD

**Issue by victor-padovam** [cybex-dev/twilio_voice#22]
I would like to understand, how does it make the request to my URL (Server), which expects this data to trigger a call?

Example my server URL is this:

`https://twillio-voice-prova.000webhostapp.com/voice-server-twilio-php/voiceCall.php`

In the function below, how do I make the request to my server URL?

```
TwilioVoice.instance.call.place( to: _controller.text, from: '7766576578657');
```

Thank you !!!

**Comment by diegog-sf** [comment]
Hello Again, and Again, please check Twilios qucickstart, you have to register that callback url in twilio, when you call 
`TwilioVoice.instance.call.place( to: _controller.text, from: '7766576578657');` twilio will call the url you specified at their dashboard.

**Comment by victor-padovam** [comment]
Thank you very much for the feedback, I'm starting now to learn about twillio using flutter.

I configured the URLs in:
**TwiML Apps: 
Voice: **https://twillio-voice-prova.000webhostapp.com/voice-server-twilio-php/makeCall.php**

and also in:   **Phone Numbers - Active Numbers**
(678) 909-1622
**https://twillio-voice-prova.000webhostapp.com/voice-server-twilio-php/incoming.php**

Can you tell me where is the correct place to configure the URL that the function `TwilioVoice.instance.call.place()`
 expects as a return in Twilio?
I thought it was in TwiML Apps

**Comment by diegog-sf** [comment]
Yes its there, and you have to use the app id in your php server when generating the accesToken

**Comment by victor-padovam** [comment]
This is my PHP code that found in the URL on my server:
 (`https://twillio-voice-prova.000webhostapp.com/voice-server-twilio-php/makeCall.php.`)
**makeCall.php:**
```
<?php
use Twilio\Rest\Client;
$to = '';
if (!empty($_GET["to"])) {
    $to = $_GET["to"];
}
if (!empty($_POST["to"])) {
    $to = $_POST["to"];
} 

$response = new Twilio\TwiML\VoiceResponse;
if (!isset($to) || empty($to)) {
  $response->say('Congratulations! You just made your first call!');
} else if (is_numeric($to)) {
 // Your Account SID and Auth Token from twilio.com/console
$account_sid = 'Axxxxxxxxx';
$auth_token = '18xxxxxxxx';
$twilio_number_from = "+16789091622";
// Where to make a voice call (your cell phone?)
$twilioApiKey = 'SKexxxxxxxx';
$twilioApiSecret = 'uxxxxxxxxx';
$client = new Twilio\Rest\Client($twilioApiKey, $twilioApiSecret, $account_sid);
 $call = $client->calls->create(  
    $to,
    $twilio_number_from,
    array(
        "url" => "http://demo.twilio.com/docs/voice.xml"
    )
);

}
echo $response;
```

configured as return in **TwiML Apps**

in my file on the server I get $to as a parameter of the function I believe it makes a request to my server and triggers the connection.
`TwilioVoice.instance.call.place( to: _controller.text, from: '7766576578657');`

However my doubt the function below `TwilioVoice.instance.call.place` already makes a POST with the data for my code to trigger call?
or she already does everything herself and what I'm doing in makeCall.php is wrong?
what return does he expect?
it waits for the return of a URL that forces the call like I did, or it waits for the JWT generated Token access
```
 TwilioVoice.instance.call.place(
                      to: '5514998100010',
                      from: '+16789091622',
                    );
```

**Comment by diegogarciar** [comment]
Closing this as it is not an issue with the package
