### ISSUE TITLE
Native Call Screen UI on iOS

### ISSUE THREAD

**Issue by nandakishorHouzeo** [cybex-dev/twilio_voice#224]
**Issue Description**:

I'm currently utilizing the latest version of the package and have successfully implemented the call functionality in Android. The Android platform supports native call screen UI functionality. However, I'm uncertain whether the same functionality is available in iOS. In my case when the call is initiated it is being shown at the status bar but when its tapped nothing is happening

**Question**:
Does the package support displaying the native call screen when making a call from an iOS device, or do we need to develop a custom user interface for this purpose?

**Comment by cybex-dev** [comment]
Hi @nandakishorHouzeo,

Apologies for the delayed response.

iOS provides their native CallKit that any app with telephonic/VoIP capabilities must utilize. A custom call screen may be developed but there are severe limitations including capturing of background microphone input/sound output that may not be transmitted if custom call screens are used.

The CallKit integrates into the iOS UI & UX and is advised to be used for this purpose.
