### ISSUE TITLE
Unregistering a Twilio instance does not end active calls on it.

### ISSUE THREAD

**Issue by yacoublambaz** [cybex-dev/twilio_voice#229]
### Steps to Reproduce

1. Make a call
2. Unregister from TwilioVoice.instance while the call is still ongoing

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Since I no longer have a token, I should be expected to be disconnected from all calls.

**Comment by bazl-E** [comment]
I think it is expected behavior, unregister call back only unregister the current token and prevent getting further calls, you should call the hangup method before calling unregister

**Comment by cybex-dev** [comment]
Hi @yacoublambaz 

Yes, this is intended behaviour as @bazl-E suggests and would be rather odd and unintuitive to have the call dropped when unregistering. This should be handled by the developer on a case by case basis.
