### ISSUE TITLE
how does receiving a call to a number that appears with the answering layout works

### ISSUE THREAD

**Issue by victor-padovam** [cybex-dev/twilio_voice#23]
```
TwilioVoice .instance.call. local (FROM: _controller.text, to : userId);
```
To work INTERNALLY the connection and be able to see on the other device playing in the background with a layout of the app itself, what is needed? The other device must have the app downloaded. o From: expect user id authenticated by firebase ?how does this work? thanks.

**Comment by VictorPadovan1997** [comment]
.

**Comment by VictorPadovan1997** [comment]
.

**Comment by diegogarciar** [comment]
Hello sorry for the late response.
For it to work you have to register both devices with your server. You can either register them with a user id or a phone number, as long as its unique its ok

**Comment by victor-padovam** [comment]
This function: 
`TwilioVoice .instance.call. local (FROM: _controller.text, to : userId);`
does she make a post request behind the scenes? passing as a parameter, from and to?

**Comment by diegogarciar** [comment]
You must have already registered your customer token, which was generated based on a twiml app which already has defined the post url in the console

**Comment by diegogarciar** [comment]
Closing this as it is not an issue with the package
