### ISSUE TITLE
FirebaseFunctions.instance.httpsCallable

### ISSUE THREAD

**Issue by victor-padovam** [cybex-dev/twilio_voice#24]
What would this function be and what does it expect in **voice-accessToken**?
Is it the token generated by my server, or the firebase user's token what would it be?

```
 final function =
        FirebaseFunctions.instance.httpsCallable("voice-accessToken");
```

**Comment by victor-padovam** [comment]
.

**Comment by diegogarciar** [comment]
This function calls the server and creates an accessToken as its using firebase the userId is used internally to generate the token for that user

**Comment by diegogarciar** [comment]
Closing this as it is not an issue with the package

**Comment by utkarsh-karnik** [comment]
Do I need to make a function for creating the accessToken in my Firebase Functions ?
