### ISSUE TITLE
Twilio Call Recording

### ISSUE THREAD

**Issue by enesuzun2002** [cybex-dev/twilio_voice#249]
### Is your proposal related to a problem?

No

Sometimes customers want the recording to be stopped.

### Describe the solution you'd like

An icon in the calling ui that stops and starts recording in twilio.

**Comment by enesuzun2002** [comment]
@husseinamar

**Comment by cybex-dev** [comment]
Good day @enesuzun2002 

I apologize for the delay in response.

Thank you for reaching out, Call Recording is something that can be done in TwiML. Stopping an active recording can also be done but must be done with an API call to your own server/TwiML App/Twilio Function.

See this for further reading: https://help.twilio.com/articles/360010199074

Adding these functions may unnecessary complicate the package with real meaningful enhancement though if further interest is shown I'll consider adding such a set of mechanisms.
