### ISSUE TITLE
How to change/override UI for receiving calls. 

### ISSUE THREAD

**Issue by Stacey940** [cybex-dev/twilio_voice#26]
Hi,

Is there a way I can change/override  UI for receiving calls and use "voip-customData" to be appear as Caller name on the incoming call and in the notifications for missed calls on android. 

Thanks

**Comment by diegogarciar** [comment]
Hi Stacey, I currently don't know how to do that without forking this project. You would need to override the android xmls and activities to achieve that. If you find an alternative to this, please let me know.

**Comment by Stacey940** [comment]
@diegogarciar Sure.  Thank you for putting hard work into making this awesome plugin.
