### ISSUE TITLE
Connection failed. Not found

### ISSUE THREAD

**Issue by ManthanSutariya** [cybex-dev/twilio_voice#27]
D/TwilioVoicePlugin( 6779): Connect failure
E/TwilioVoicePlugin( 6779): Call Error: 31404, Not Found

 I am trying to call a physical number, and I am using the correct access token but don't know why I am facing this error.

**Comment by diegogarciar** [comment]
I think this should be properly configured in a server, have you managed to call a user using the example native apps from twilio?

**Comment by diegogarciar** [comment]
Please see #28

**Comment by cybex-dev** [comment]
Closing due top lack of responses, feedback or activity.
