### ISSUE TITLE
Can't deploy firebase functions

### ISSUE THREAD

**Issue by zamarwells** [cybex-dev/twilio_voice#28]
i used the example firebase function you posted but i keep getting the error below.
Unhandled error ReferenceError: helpers is not defined
    at /workspace/index.js:7:20
    at fixedLen (/workspace/node_modules/firebase-functions/lib/providers/https.js:66:41)
    at /workspace/node_modules/firebase-functions/lib/common/providers/https.js:322:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 

i don't really know much about cloud functions but it seems i'm missing and import statement. please help

**Comment by diegogarciar** [comment]
Hey @zamarwells 
replace that function with
```js
if (typeof (context.auth) === 'undefined') {
      throw new functions.https.HttpsError('unauthenticated', 'The function must be called '
        + 'while authenticated');
    }
 let userId = context.auth.uid;

```

**Comment by diegogarciar** [comment]
You must have your user authenticated in the app via firebase auth for it to work.

**Comment by zamarwells** [comment]
Thanks @diegogarciar , I really appreciate the quick response, I've updated my Firebase Functions and its been deployed, access token are being generated and received in my Flutter app, but i now have two new errors, one was previously mentioned in an "open Issue", i don't really know if i should keep communicating with you here or open new issues for the errors i have, none the less, here are my errors below, I'd really appreciate some more help.... Thanks

first error
I/TwilioVoicePlugin( 5105): Registering with FCM
E/TwilioVoicePlugin( 5105): Registration Error: 31400, Bad Request


second error
D/TwilioVoicePlugin( 5105): Connect failure
E/TwilioVoicePlugin( 5105): Call Error: 31404, Not Found
I/flutter ( 5105): Call Error: 31404, Not Found

There's an open issue for the second error already but no solution there

**Comment by zamarwells** [comment]
I've been able to solve this issue, the error was not coming from the twilio_voice package, for those that are  still facing this issue. The problem occurs when u fail to configure a url for your Twiml app, do so with this command below

twilio api:core:applications:create --friendly-name=my-twiml-app --voice-method=POST --voice-url="https://my-quickstart-dev.twil.io/make-call"

**Comment by diegogarciar** [comment]
Nice catch, yes that was my guess too but I couldn’t replicate the issue.
