### ISSUE TITLE
 Android resource linking failed

### ISSUE THREAD

**Issue by zamarwells** [cybex-dev/twilio_voice#29]
I have been building with my emulator and i decided to build a release apk to test on my physical device but I'm getting this error even though i already put the splach_icon in drawable folder, see project tree below

![debug sample](https://user-images.githubusercontent.com/91335248/135081982-ca62808b-0f06-4c6d-be3a-98d4a601d236.png)

flutter doctor
![flutter doctor](https://user-images.githubusercontent.com/91335248/135096820-9872dc0c-a2bd-48f4-9835-0b840e5fbc29.png)

Execution failed for task ':twilio_voice:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\twilio_voice-0.0.9\android\src\main\res\layout\activity_answer.xml:17: AAPT: error: resource drawable/splash_icon (aka com.twilio.twilio_voice:drawable/splash_icon) not found.

**Comment by zamarwells** [comment]
@diegogarciar , Please is there anyway to bypass this error?

**Comment by diegogarciar** [comment]
Hey sorry, so I actually have it as this in my project
<img width="499" alt="image" src="https://user-images.githubusercontent.com/17276155/137437921-6809e9e9-be75-4217-8ee4-b2d1d56c8ac8.png">

**Comment by EngYasmeenMahmoud** [comment]
please solve this issue

**Comment by EngYasmeenMahmoud** [comment]
i solve this issue by creating new repsitory  and add splash_icon to drawable folder and import twilio voice n my application as this  
twilio_voice:
    git:
      url: https://github.com/EngYasmeenMahmoud/twilio.git
      ref: master

**Comment by diegogarciar** [comment]
Hello, Yes, that's what I meant in the image above

**Comment by diegogarciar** [comment]
You should add it in your own android project so that you can customize the image

**Comment by EngYasmeenMahmoud** [comment]
i do that in my android but not work in release it work only in debug
after make above solution it work

**Comment by cybex-dev** [comment]
Closing due top lack of responses, feedback or activity.
