### ISSUE TITLE
Unable to open own screen after answring the call at reveicer side

### ISSUE THREAD

**Issue by rajneeshkumarVayuz** [cybex-dev/twilio_voice#3]
`TwilioVoice.instance.callEventsListener.listen((event) {
      switch (event) {
        case CallEvent.answer:
          try{
            // TwilioVoice.instance.showBackgroundCallUI();
            // ShowToast.show('Answer');
            Navigator.push(
                context,
                MaterialPageRoute(
                    builder: (context) => AudioCall(
                      token: "",
                      clientId: "",
                      isCall: false,
                    )));
          }catch(e){
            print("error --> $e");
          }

          break;
        case CallEvent.ringing:
          {
            ShowToast.show('Ringing');
            break;
          }
        case CallEvent.connected:
          break;
        case CallEvent.callEnded:
          ShowToast.show('callEnded');
          Navigator.pop(context);
          break;
        case CallEvent.unhold:
        // TODO: Handle this case.
          break;
        case CallEvent.hold:
        // TODO: Handle this case.
          break;
        case CallEvent.unmute:
        // TODO: Handle this case.
          break;
        case CallEvent.mute:
        // TODO: Handle this case.
          break;
        case CallEvent.speakerOn:
        // TODO: Handle this case.
          break;
        case CallEvent.speakerOff:
        // TODO: Handle this case.
          break;
        case CallEvent.log:
        // TODO: Handle this case.
          break;
      }
    });`

**Comment by diegogarciar** [comment]
Please refer to the example listener

``` dart
void waitForCall() {
    checkActiveCall();
    TwilioVoice.instance.callEventsListener
      ..listen((event) {
        print("voip-onCallStateChanged $event");

        switch (event) {
          case CallEvent.answer:
            //at this point android is still paused
            if (Platform.isIOS && state == null ||
                state == AppLifecycleState.resumed) {
              pushToCallScreen();
              hasPushedToCall = true;
            }
            break;
          case CallEvent.connected:
            if (Platform.isAndroid &&
                TwilioVoice.instance.call.activeCall!.callDirection ==
                    CallDirection.incoming) {
              if (state != AppLifecycleState.resumed) {
                TwilioVoice.instance.showBackgroundCallUI();
              } else if (state == null || state == AppLifecycleState.resumed) {
                pushToCallScreen();
                hasPushedToCall = true;
              }
            }
            break;
          case CallEvent.callEnded:
            hasPushedToCall = false;
            break;
          default:
            break;
        }
      });
  }

```

It seems that the answer event is not received on time as the app is still in background or killed for android devices, for this reason we wait until "connected" event and check that the platform is android and the call is incoming. In the example, I also check the call state at initialization as the app might have launched due to an incoming call and answer event is lost

**Comment by rajneeshkumarVayuz** [comment]
Please refer a complete example if there is any because in some devices also call notification is not coming and in some devices answer button is not working when app is not in running task.

**Comment by diegogarciar** [comment]
you can find the example here
https://github.com/diegogarciar/twilio_voice/blob/master/example/lib/main.dart
