### ISSUE TITLE
Change the custom UI when receiving an incoming call in android

### ISSUE THREAD

**Issue by Farhannadeer** [cybex-dev/twilio_voice#30]
When receiving an incoming call, it is pushing to a custom UI written in the package, I want to show a UI which I have designed, when pushing to the designed UI for answering the call the custom UI is dominating, is there a way to disable the custom UI for answering the call?

**Comment by diegogarciar** [comment]
Hello, I don't think it's possible without forking the repo and customizing the UI in your branch. If you find another way to do it without working, please let me know
