### ISSUE TITLE
[firebase_functions/not-found] NOT_FOUND

### ISSUE THREAD

**Issue by victor-padovam** [cybex-dev/twilio_voice#32]
In function :

```
 registerUser() async {
    print("voip-registtering with token ");
    print("voip-calling voice-accessToken");
    final function =
        FirebaseFunctions.instance.httpsCallable("voice-accessToken");
    print(function);

    final data = {
      "platform": Platform.isIOS ? "iOS" : "Android",
    };

    final result = await function.call(data);
```
Exception : 
```
Exception has occurred.
FirebaseFunctionsException ([firebase_functions/not-found] NOT_FOUND
```

My pubspec.yaml:
`  cloud_functions: ^3.0.2`
[https://i.ibb.co/9GkkK0d/Captura-de-Tela-2021-10-14-a-s-20-18-30.png](url)

**Comment by diegogarciar** [comment]
Hello, this is just an example, you must use use you own way to call your server to receive the access token, this example asumes that you have deployed a cloud function into your firebase server.

**Comment by diegogarciar** [comment]
Victor, this space is for submitting issues, this is not customer support. Please read carefully the readme and the manuals provided by Twilio, and inspect the code behind the scenes to se how it's working.

If you still need customer support, try reaching Twilio as this is a third party package.

**Comment by victor-padovam** [comment]
Thank you very much for the feedback.

My questions are related to your package and not twillio.
the package calls different methods and functions that does not speak in readme
.
but thank you
