### ISSUE TITLE
error in create release version

### ISSUE THREAD

**Issue by EngYasmeenMahmoud** [cybex-dev/twilio_voice#35]
* What went wrong:
Execution failed for task ':twilio_voice:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     /Users/yasmeenmahmoud/flutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/twilio_voice-0.0.9/android/src/main/res/layout/activity_answer.xml:17: AAPT: error: resource drawable/splash_icon (aka com.twilio.twilio_voice:drawable/splash_icon) not found.

     /Users/yasmeenmahmoud/flutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/twilio_voice-0.0.9/android/src/main/res/layout/activity_background_call.xml:18: AAPT: error: resource drawable/splash_icon (aka com.twilio.twilio_voice:drawable/splash_icon) not found.

**Comment by diegogarciar** [comment]
Hello, have you follow the steps for pro guard file?

**Comment by EngYasmeenMahmoud** [comment]
hello,
where this file??
i searched for this issue and find this solution
and now it work fine

**Comment by AnnieNinaJoyceV** [comment]
@EngYasmeenMahmoud Can you please share how you were able to resolve it? I have encountered the same issue. Thanks!

**Comment by EngYasmeenMahmoud** [comment]
i solve this issue by creating new repsitory and add splash_icon to drawable folder and import twilio voice n my application as this
twilio_voice:
git:
url: https://github.com/EngYasmeenMahmoud/twilio.git
ref: master

**Comment by diegog-sf** [comment]
You must register the splash_icon in your res folder as follows. If you register it inside the package, it will not be customizable, that's why its not done there. I'll document this later on.

![image](https://user-images.githubusercontent.com/87551320/138295312-cadf7f8e-8795-40a7-98ef-ebca12cf6304.png)

**Comment by AnnieNinaJoyceV** [comment]
@diegog-sf I tried by adding the splash icon, but it gives the same error with the following command

`flutter build apk -t lib/main_stag.dart --no-shrink --obfuscate --split-debug-info build/app/outputs/symbols`

_Error_

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':twilio_voice:verifyReleaseResources'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
>    > 1 exception was raised by workers:
>      com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
>      /Users/joyce/development/flutter/.pub-cache/hosted/pub.dartlang.org/twilio_voice-0.0.9/android/src/main/res/layout/activity_answer.xml:17: AAPT: error: resource drawable/splash_icon (aka com.twilio.twilio_voice:drawable/splash_icon) not found.
> 
>      /Users/joyce/development/flutter/.pub-cache/hosted/pub.dartlang.org/twilio_voice-0.0.9/android/src/main/res/layout/activity_background_call.xml:18: AAPT: error: resource drawable/splash_icon (aka com.twilio.twilio_voice:drawable/splash_icon) not found.

<img width="288" alt="Screenshot 2021-10-27 at 6 55 34 PM" src="https://user-images.githubusercontent.com/7369485/139075343-e3e6e8e9-e42c-48d1-83d3-d4a94ba79891.png">

**Comment by diegogarciar** [comment]
Hello, Try putting them in drawable-XXX folders
![image](https://user-images.githubusercontent.com/87551320/138295312-cadf7f8e-8795-40a7-98ef-ebca12cf6304.png)

**Comment by AnnieNinaJoyceV** [comment]
Oh, sorry didn’t notice the folder names. I will try this and update tomorrow. Thanks!

**Comment by AnnieNinaJoyceV** [comment]
@diegogarciar I tried putting them inside drawable-{-} folders, even then it didn't work. But, using @EngYasmeenMahmoud fork, builds without issues.

**Comment by diegogarciar** [comment]
Thanks @AnnieNinaJoyceV for letting me know, and have you checked out which image it ended up using when receiving a call in the background, you're or his?

**Comment by AnnieNinaJoyceV** [comment]
My app doesn’t use incoming call feature, or the CallKit feature in general. So I cannot test with that scenario. Is there some other way I can test it?

**Comment by diegogarciar** [comment]
No I don't think so, but thank you anyway!

**Comment by arvie9** [comment]
Any clear solution on this? Just ran into this issue when trying to make an APK build. Runs fine on the emulator though.
I have the splash_icon.png on the drawable and mipmap folders but still run into this error during build.

**Comment by cybex-dev** [comment]
Closing.
