### ISSUE TITLE
AndroidManifest.xml the service  incomming call notifications

### ISSUE THREAD

**Issue by victor-padovam** [cybex-dev/twilio_voice#38]
Referente ao README In AndroidManifest.xml the service  incomming call notifications:

```
  <service
      android:name="com.twilio.twilio_voice.fcm.VoiceFirebaseMessagingService"
      android:stopWithTask="false">
      <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
  </service>
```

I configured my app to FCM, I manage to trigger a notification for the app is working.
he returns this to me on the terminal but I received the notification:

`E/FlutterFcmService(20920): The message was not a valid Twilio Voice SDK payload: {body=recive, title=teste, click_action=com.twilio.twilio_voice.fcm.VoiceFirebaseMessagingService}`

I need to configure the **android:name=** or the app somewhere on twilio or the package does it all by itself?
Thank you for help.

**Comment by diegogarciar** [comment]
Is that a custom notification? if yes you can disregard this message. 
This will detect all notifications and act when it receives a call notification, it will ignore all others

**Comment by diegogarciar** [comment]
Is that a custom notification? if yes you can disregard this message. 
This will detect all notifications and act when it receives a call notification, it will ignore all others

**Comment by victor-padovam** [comment]
Exact was a custom notification to test the FCM integration.
thank you
