### ISSUE TITLE
pushCredentialSid

### ISSUE THREAD

**Issue by victor-padovam** [cybex-dev/twilio_voice#39]
I was checking the repository's **function.js** file to compare how you generate the **accessToken** for an identifier and I noticed that you're passing the **pushCredentialSid** method something I wasn't doing on my server.

According to your function below you check the device if it is android : **android_push_sid** else **ios_push_sid**

how was a Sid generated for **android** and **ios**?
because following the twillio documentation:
[https://www.twilio.com/docs/conversations/android/push-notifications](https://www.twilio.com/docs/conversations/android/push-notifications)

They pass it like **pushCredentialSid** is the console's **Push Crendecial** configured just right, so it's just **ONE** pushCredentialSid, ​​not one for android and one for ios.
Thank you for me help.

```
 if (payload.platform === 'iOS') {
    console.log('creating access token for iOS');
    pushCredSid = payload.production ? twilioConfig.apple_push_sid_release
      : (twilioConfig.apple_push_sid_debug || twilioConfig.apple_push_sid_release);
  } else {
    console.log('creating access token for Android');
    pushCredSid = twilioConfig.android_push_sid;
  }
```

**Comment by diegogarciar** [comment]
The guide you provided is for setting up android push notifications, there's another guide for iOS push notification and you create another SID for iOS. 
https://www.twilio.com/docs/conversations/ios/push-notifications-ios

**Comment by victor-padovam** [comment]
Oh now I understand
following the documentation for android it asks to create an **FCM** credential.:
https://www.twilio.com/docs/conversations/android/push-notifications

Following the IOS documentation he asks to create an **APN** type credential
https://www.twilio.com/docs/notify/configure-ios-push-notifications

So the difference is that for android **Sid** is the credential generated for **FCM** and for **IOS** it is **APN**
Its correct ?

**Comment by diegogarciar** [comment]
Yes

**Comment by victor-padovam** [comment]
Perfect, thank you me help .
I've been implementing this for a week now.
