### ISSUE TITLE
Not able to receive own notification which are sending from own server

### ISSUE THREAD

**Issue by rajneeshkumarVayuz** [cybex-dev/twilio_voice#5]
I am not able to receive notification from the server if i register 
`        <service
            android:name="com.twilio.twilio_voice.fcm.VoiceFirebaseMessagingService"
            android:stopWithTask="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>`

this service in the project AndroidManifest.xnl file or if i don't register this service in AndroidManifest.xml then i am not getting call notification. How i solve this case please provide some solution.

**Comment by diegogarciar** [comment]
What service are you using to send the push notifications? Also are you using a package to receive them?

**Comment by rajneeshkumarVayuz** [comment]
Yes i am using firebase to send the notification and i am using
firebase_messaging package to handle notification but after using the
twilio_voice package my server fcm notifications are not working

**Comment by diegogarciar** [comment]
Nice, me too, are you using firebase messaging above version 8.0.0?

**Comment by rajneeshkumarVayuz** [comment]
No i am using firebase messaging version 7.0.3

**Comment by rajneeshkumarVayuz** [comment]
is there any solution for the same?

**Comment by diegogarciar** [comment]
Then I strongly suggest you update to version 9, if you can't you will need to override the same firebase messaging service and create your own.

As reference, this is the one I had when I was using firebase below 8, some firebase settings might be different so I suggest you start from scratch from the service firebase is using at version 7.0.3.

https://github.com/diegogarciar/flutter_twilio_voice/blob/2e52ab51ee086c7bf32191d67174b4cc776d9176/android/src/main/java/com/dormmom/flutter_twilio_voice/fcm/VoiceFirebaseMessagingService.java

**Comment by diegogarciar** [comment]
Sorry it was actually this file
https://github.com/diegogarciar/flutter_twilio_voice/blob/5f9318131e7b816cc352f65552b476c7ea0f21a2/android/src/main/java/com/dormmom/flutter_twilio_voice/fcm/VoiceFirebaseMessagingService.java


Just completely remove this part
``` java
  if (valid) {
                return;
//                Log.e(TAG, "The message was not a valid Twilio Voice SDK payload: " +
//                  remoteMessage.getData());
            }
```

**Comment by rajneeshkumarVayuz** [comment]
Is there any solution of receiving 2 same push notification at same time after updating the firebase-messaging version to 9.1.2?

**Comment by diegogarciar** [comment]
Are the push notifications twilio call notifications or normal fcm notifications?

**Comment by rajneeshkumarVayuz** [comment]
normal fcm notification

**Comment by diegogarciar** [comment]
have you removed the original firebase messaging service in the android manifest? you should only have registered this package's service

`<service android:name="com.twilio.twilio_voice.fcm.VoiceFirebaseMessagingService" android:stopWithTask="false"> <intent-filter> <action android:name="com.google.firebase.MESSAGING_EVENT" /> </intent-filter> </service>
`

**Comment by rajneeshkumarVayuz** [comment]
yes
