### ISSUE TITLE
Closed app does not receive incoming calls after Twilio Token expires

### ISSUE THREAD

**Issue by cybex-dev** [cybex-dev/twilio_voice#50]
**Summary:**

App that hasn't been open for e.g. 2 days (with expired token) will not receive call intent/notification nor generate new token and process notification.

---

**Details/Questions/Solutions:**

This issue has a few StackOverflow questions asked but non have workable solutions or any good documentation to follow (atleast what I found).

- [Android Twilio Token expiration While the app is in background](https://stackoverflow.com/questions/25931738/android-twilio-token-expiration-while-the-app-is-in-background)
- [Token expiration in Twilio](https://stackoverflow.com/questions/39216766/token-expiration-in-twilio)

Some answers suggest using the `stopListening() function, looking through the API docs for [Twilio's Android API](https://twilio.github.io/twilio-voice-android/docs/latest/), I don't find any method/function named or similar to `stopListening()`. From context, I assume this refers to the `token is expiring` function but nothing related to a token expiring while app is closed. 

**Thus, after the token expires and app is closed for more than a day, no calls will be received - this is a problem!**

---

**Log output:**

When call is received on device with expired token that is (force closed), the only console output with own package name `$ adb logcat | grep com.myawesome.app`:

```bash
11-03 11:16:31.307 29039 29039 W GCM     : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=com.myawesome.app (has extras) }
```

output for `$ adb logcat | grep com.twilio.twilio_voice`:
_nothing_

**Steps to reproduce:**
1. Setup App
2. Setup TwiML `make-call` endpoint
3. Acquire valid tokens (valid for e.g. 5min) and confirm push notifications work.
4. Install on 2 devices
5. **Device 1**, close app completely (i.e. force kill), on **Device 2** leave app open
6. after e.g. 6min (assuming 5min expiry), make call on **Device 2** (your app should handle expired tokens, acquires new tokens and place call)
7. Device 1 will receive broadcast intent only but will not ring or perform any action.

---

**Setup & devices tested on:** (Android & iOS) in sandbox & (iOS) production

```bash
C:\Users\CybeX\FlutterProjects\twilio_voice\example>flutter doctor -v
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1288], locale en-ZA)
    • Flutter version 2.5.3 at C:\Users\CybeX\.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\CybeX\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\CybeX\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\CybeX\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at C:\Users\CybeX\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\201.7223.91
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\CybeX\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7142.45
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7665

[√] Connected device (6 available)
    • SM N975U1 (mobile) • RF8MC02F23L • android-arm64  • Android 11 (API 30)
    • SM A217F (mobile)  • RF8N51V8G3E • android-arm64  • Android 10 (API 29)
    • iPhone 6s (mobile)  • iOS (13.6.1)
    • iPhone 7 (mobile)  • iOS (14.4.1)
    • SM A217F (mobile)  • RF8N51V8G3E • android-arm64  • Android 10 (API 29)
    • Chrome (web)       • chrome      • web-javascript • Google Chrome 95.0.4638.54
    • Edge (web)         • edge        • web-javascript • Microsoft Edge 95.0.1020.30

• No issues found!
```

**Comment by diegogarciar** [comment]
Hi @cybex-dev! I think this is an issue with the Twilio SDK itself that maybe should be reported directly to them.

https://github.com/twilio/voice-quickstart-ios
https://github.com/twilio/voice-quickstart-android/

**Comment by VictorPadovan1997** [comment]
the package does not offer a treatment for this?

**Comment by victor-padovam** [comment]
@cybex-dev i was thinking about running background tasks in flutter which updates the token every hour.
https://youtu.be/NhlPK10_k9E

**Comment by cybex-dev** [comment]
I need to confirm this is not an issue on my end - after some extensive testing I noticed that I wasn't refreshing the token correctly on the caller. I will confirm this is not an issue and an oversight on my end in the next few hours.

**Comment by victor-padovam** [comment]
did you work with background tasks in flutter to update the expired token? some package or native?

**Comment by cybex-dev** [comment]
@VictorPadovan1997 no, using just this package which did all background processing, etc. I'm using the package [get_it](https://pub.dev/packages/get_it) to assist in getting service instances and using stream subscriptions, etc but no other background tasks.

**Comment by diegogarciar** [comment]
@cybex-dev I have never experience Your issue, thats why I was not sure about it. But the caller does have to refresh the token. I can send text snippet in a few hours on how to auto update it

**Comment by victor-padovam** [comment]
great, send ... will help me too.

**Comment by victor-padovam** [comment]
> @ VictorPadovan1997 não, usando apenas este pacote que fez todo o processamento em segundo plano, etc. Estou usando o pacote [get_it](https://pub.dev/packages/get_it) para ajudar na obtenção de instâncias de serviço e usando assinaturas de fluxo, etc., mas nenhuma outra tarefa em segundo plano.


@cybex-dev Were you able to use the components of this package to change the token in the background?
here don't mention this in the readme 🤔

**Comment by diegogarciar** [comment]
Hello, do you already have registered OnDeviceTokenChanged? It fetches a new device token when we receive a token error, this might fail once on the first call and then succeed on the second.

```dart
 _register();

    _twilioVoice.setOnDeviceTokenChanged((token) {
      print("voip-device token changed");
      _register();
    });
```

I do have a more complex code in a native implementation where I check save the expiration of it and refresh then needed, but I have never needed it on this package flutter.

**Comment by cybex-dev** [comment]
@VictorPadovan1997 @diegogarciar apologies for not getting back sooner.

Having done more testing my side, I can confirm this is a non-issue, a simple check failed my end which is not rectified. My expiry check failed and so new tokens weren't being generated causing the calls not to go through. Since this is an issue on my side, I will be closing as everything works exactly as expected.
