### ISSUE TITLE
I'm having trouble getting calls when the app is closed in the background.

### ISSUE THREAD

**Issue by victor-padovam** [cybex-dev/twilio_voice#54]
Good afternoon.

I'm having trouble getting calls when the app is closed in the background.

Situation:
I close the entire app in the background (shut down), When I get a call from a device it shows the notification that they are calling me and shows the notification with the option 'Answer'.

When clicking 'Answer' instead of opening the app and showing the call screen, nothing happens.

video for exemple: [https://drive.google.com/file/d/1IQ9_UO_u7V7AmgwOPA5E2x8SF6Zgs5aV/view?usp=sharing](https://drive.google.com/file/d/1IQ9_UO_u7V7AmgwOPA5E2x8SF6Zgs5aV/view?usp=sharing)

**Comment by victor-padovam** [comment]
@cybex-dev any solution  for me help ? 
Thankss.

**Comment by diegogarciar** [comment]
Closing this as duplicate for #17
