### ISSUE TITLE
From and To values passed null on Ringing and show call error 31603, Decline

### ISSUE THREAD

**Issue by RahiPatel25** [cybex-dev/twilio_voice#55]
Hello, I got this call error 31603, Decline when I use our working accessToken..

**Comment by cybex-dev** [comment]
> Hello, I got this call error 31603, Decline when I use our working accessToken..

Did you set up your TwiML functions as documented in the QuickStart section of the ReadME? https://github.com/diegogarciar/twilio_voice#twilio-setupquickstart-help

**Comment by RahiPatel25** [comment]
Yes, Our access token is working on native language with same flow of Twilio..

**Comment by cybex-dev** [comment]
> Yes, Our access token is working on native language with same flow of Twilio..

I noticed this issue occurs only if no TwiML function is setup or request URL is available for use. This solution (as is) works for my app in production. Please review your Twilio logs to ensure you don't have any errors/call fails from Flutter.

**Comment by cybex-dev** [comment]
Closing due top lack of responses, feedback or activity.
