### ISSUE TITLE
Ringing - From: null, To: null, Direction: CallDirection.outgoing

### ISSUE THREAD

**Issue by Erchil66** [cybex-dev/twilio_voice#56]

**Comment by diegogarciar** [comment]
Please provide a full description of the issue with reproducible steps and expected behavior, otherwise I'll close this.

**Comment by Erchil66** [comment]
@diegogarciar Hi this is my problem in my logs does it on the problem was on my twilio?


[log] voip-onCallStateChanged CallEvent.ringing
I/flutter (15419): Ringing - From: null, To: null, Direction: CallDirection.outgoing
2
[log] voip-onCallStateChanged CallEvent.ringing
I/chatty  (15419): uid=10190(com.bettercliniq.app) 1.ui identical 1 line
I/flutter (15419): Ringing - From: null, To: null, Direction: CallDirection.outgoing

**Comment by Erchil66** [comment]
I solve the problem was on my twilio i was block by the server side

**Comment by cybex-dev** [comment]
@Erchil66 would you mind providing some additional info to what caused and also resolved your problem?

**Comment by Erchil66** [comment]
@cybex-dev the cause was on my side in my backend on my backend we have our own server called phone server also the phone server provide me some token for twilio so the phone server now will identify if this person is enable to connect me although using dev production so in my backend side they need me to give some open line in order for me to call somebody .

at first i need them to look on the logs from twilio if am having an error logs or entry to call.
as the error logs shown me as "**HTTP Connection Failure - Read Time-out**" which the url am gonna access is not open to me yet.
