### ISSUE TITLE
AUDIO_OUTPUT_FLAG_FAST denied, rates do not match 44100 Hz, require 48000 Hz

### ISSUE THREAD

**Issue by preprincipletech** [cybex-dev/twilio_voice#58]
![Screenshot from 2021-11-25 19-42-13](https://user-images.githubusercontent.com/85453484/143458500-788bf9f8-f240-46ff-86cd-ef66bf698fd1.png)

 WebRtcAudioRecordExternal: verifyAudioConfig: PASS
I/tvo.webrtc.Logging( 3801): WebRtcAudioRecordExternal: stopRecording
I/tvo.webrtc.Logging( 3801): WebRtcAudioRecordExternal: stopThread
I/tvo.webrtc.Logging( 3801): WebRtcAudioRecordExternal: doAudioRecordStateCallback: STOP
I/tvo.webrtc.Logging( 3801): WebRtcAudioEffectsExternal: release
I/tvo.webrtc.Logging( 3801): WebRtcAudioRecordExternal: releaseAudioResources
I/tvo.webrtc.Logging( 3801): VolumeLogger: stop@[name=MediaFactoryImp - 4068, id=4703]
I/tvo.webrtc.Logging( 3801): WebRtcAudioTrackExternal: stopPlayout
I/tvo.webrtc.Logging( 3801): WebRtcAudioTrackExternal: underrun count: 0
I/tvo.webrtc.Logging( 3801): WebRtcAudioTrackExternal: stopThread
I/tvo.webrtc.Logging( 3801): WebRtcAudioTrackExternal: Stopping the AudioTrackThread...
I/tvo.webrtc.Logging( 3801): WebRtcAudioTrackExternal: AudioTrackThread has now been stopped.
I/tvo.webrtc.Logging( 3801): WebRtcAudioTrackExternal: Calling AudioTrack.stop...
D/AudioTrack( 3801): stop() called with 44640 frames delivered
I/tvo.webrtc.Logging( 3801): WebRtcAudioTrackExternal: AudioTrack.stop is done.
I/tvo.webrtc.Logging( 3801): WebRtcAudioTrackExternal: doAudioTrackStateCallback: 1
I/tvo.webrtc.Logging( 3801): WebRtcAudioTrackExternal: releaseAudioResources
D/TwilioVoicePlugin( 3801): Disconnected
I/flutter ( 3801): voip-onCallStateChanged CallEvent.callEnded
W/AudioTrack( 3801): AUDIO_OUTPUT_FLAG_FAST denied, rates do not match 44100 Hz, require 48000 Hz
I/flutter ( 3801): voip-onCallStateChanged CallEvent.callEnded
I/flutter ( 3801): call Ended

**Comment by diegogarciar** [comment]
Please provide a full description of the issue with reproducible steps and expected behavior, otherwise I'll close this.
