### ISSUE TITLE
ios not receive incoming call

### ISSUE THREAD

**Issue by EngYasmeenMahmoud** [cybex-dev/twilio_voice#59]
i did calling and receive incoming call in android successfully, but in ios i can only make call not able to receive incoming call
i did these
https://developer.clevertap.com/docs/how-to-create-an-ios-apns-certificate#section-convert-the-cer-file-to-a-p-12-certificate
https://github.com/twilio/voice-quickstart-ios#6-create-a-push-credential-with-your-voip-service-certificate
but can't get incoming call
can you help me???

**Comment by cybex-dev** [comment]
Review this: https://github.com/diegogarciar/twilio_voice#ios

**Comment by cybex-dev** [comment]
@EngYasmeenMahmoud did you find a solution?

**Comment by chrisdjin** [comment]
@cybex-dev I've had the same issue and banged my head on the wall for one week! Whew, this solves the problem. @EngYasmeenMahmoud Did this work for you?

**Comment by Erchil66** [comment]
Does this Solve? am also having a bit problem also on to this i can make outgoing call but in receiving not.

btw. i used Simulator

**Comment by cybex-dev** [comment]
> Does this Solve? am also having a bit problem also on to this i can make outgoing call but in receiving not.
> 
> btw. i used Simulator

~~if I'm not mistaken, there are issues regarding push notifications and the iOS simulator. I'd suggest reading up on that.~~

scratch that, since XCode 11.4 it is possible to do so.

**Comment by cybex-dev** [comment]
@Erchil66 I'd suggest starting to debug in Twilio. When you call is placed, it goes to the Twilio e.g. "/make-call" (that is the route to execute the dial function). 

**Start with Twilio:**
You have multiple tools to assist in debugging the problem:
1. the [Twilio functions debugger](https://www.twilio.com/docs/runtime/functions/debugging), and
2. the Twilio errors (from Twilio dashboard). 

Review those to see if a call is infact placed.  If there is no Twilio problem, try looking at:

**XCode Capabilities:**
Ensure you have: 
- `push notifications` capability, 
- `background fetch` capability, and 
- `voip` capability
set for your project - [see this for more info](https://github.com/twilio/voice-quickstart-ios#7-receive-an-incoming-call)

**Environment & Twilio Tokens:** [see for more info](https://developer.apple.com/go/?id=push-notifications)
Lastly, ensure the environment you are using is set correctly (if not, you'll receive a bunch of Twilio errors). iOS has 2 environments, development and production each with their own APNS server. Make sure that your Twilio CRXXXX key is used in the correct environment.

When making a request for a Twilio token (from your server), pass through the [Platform.isAndroid](https://api.flutter.dev/flutter/dart-io/Platform/isAndroid.html) / [Platform.isIOS](https://api.flutter.dev/flutter/dart-io/Platform/isIOS.html) and the [kReleaseMode](https://api.flutter.dev/flutter/foundation/kReleaseMode-constant.html) flag to check which CRXXXX Twilio key should be used to generate tokens. #cloud-functions-step-3-generate-access-tokens-via-cloud-function

**Comment by Erchil66** [comment]
@cybex-dev thanks for the reply will follow on this.

**Comment by Erchil66** [comment]
@cybex-dev  am having a problem i always get invalid token although i set the things needed in twilio i used prod not on sandbox. and am still also using simulator. Please help.

**Comment by Erchil66** [comment]
@cybex-dev can i ask on this problem i've been stuck here for almost days don't know where to start.

as the twilio logs no error as for the capabilities are all set and good with the certificates on dev-app.

the problem am getting is that i have a token working on prod i do successfully call outgoing but when try to get incoming call on app it wont ring but it goes to the fallback number that i set. Which am having right now.

**Comment by cybex-dev** [comment]
> @cybex-dev can i ask on this problem i've been stuck here for almost days don't know where to start.
> 
> as the twilio logs no error as for the capabilities are all set and good with the certificates on dev-app.
> 
> the problem am getting is that i have a token working on prod i do successfully call outgoing but when try to get incoming call on app it wont ring but it goes to the fallback number that i set. Which am having right now.

which devices are you working on iOS or Android?

**Comment by Erchil66** [comment]
> > @cybex-dev can i ask on this problem i've been stuck here for almost days don't know where to start.
> > as the twilio logs no error as for the capabilities are all set and good with the certificates on dev-app.
> > the problem am getting is that i have a token working on prod i do successfully call outgoing but when try to get incoming call on app it wont ring but it goes to the fallback number that i set. Which am having right now.
> 
> which devices are you working on iOS or Android?

IOS device. And also using prod. And for some reason the Event Call.answer won't show on log.

**Comment by cybex-dev** [comment]
> > > @cybex-dev can i ask on this problem i've been stuck here for almost days don't know where to start.
> > > as the twilio logs no error as for the capabilities are all set and good with the certificates on dev-app.
> > > the problem am getting is that i have a token working on prod i do successfully call outgoing but when try to get incoming call on app it wont ring but it goes to the fallback number that i set. Which am having right now.
> > 
> > 
> > which devices are you working on iOS or Android?
> 
> IOS device. And also using prod. And for some reason the Event Call.answer won't show on log.

My best suggestion at this point would be to start with Android if you can and confirm it works there. If that works, then try the [twilio-ios-starter](https://github.com/twilio/voice-quickstart-ios) application and change it to call "the other device".  Once you have that sorted, review the [ReadMe](https://github.com/diegogarciar/twilio_voice/blob/master/README.md) file and ensure you have reviewed everything. Once complete, I believe you will have a working solution.

At this point, there may be nothing wrong or multiple errors - this is the best approach I can suggest.

**Comment by Erchil66** [comment]
@cybex-dev really thanks for the help i able to receive incoming call now although the problem is the name is unknown caller
as my mistake was i bet in my plist
![Inkedimage_from_ios_720_LI](https://user-images.githubusercontent.com/92772509/154292585-13ea3180-1a4e-4b8e-8840-22af93796add.jpg)

i made to many changes in app to many as per i remember in my plist is t just FirebaseAppDelegateProxyEnabled to true not false don't know if this the one. then other things for set on dashboard in Twilio

**Comment by dk3030** [comment]
Hey Can You Please Provide Solution I'm Not Able To Receiving Call in IOS I Have Performed All This Above Steps In My Code
https://developer.clevertap.com/docs/how-to-create-an-ios-apns-certificate#section-convert-the-cer-file-to-a-p-12-certificate
https://github.com/twilio/voice-quickstart-ios#6-create-a-push-credential-with-your-voip-service-certificate
and also perform https://github.com/twilio/voice-quickstart-ios this steps also but not getting incoming call on IOS 15 IPhone Please Provide me Solution What I Do ?

**Comment by alzihadi** [comment]
@dk3030 review this as @cybex-dev suggested earlier: 

**XCode Capabilities:** Ensure you have:

* `push notifications` capability,
* `background fetch` capability, and
* `voip` capability


**Add this in info.plist:** 

```
<key>FirebaseAppDelegateProxyEnabled</key>
<true/>
```

**Comment by alzihadi** [comment]
@cybex-dev how to show the caller number in the place of 'Unknown Caller' here?
.

![344795899_1327850721447628_2100529388347079606_n](https://github.com/diegogarciar/twilio_voice/assets/81793100/f0771c3c-2bdc-463c-a60d-9c40a6af5592)

**Comment by cybex-dev** [comment]
> @cybex-dev how to show the caller number in the place of 'Unknown Caller' here? .
> 
> ![344795899_1327850721447628_2100529388347079606_n](https://user-images.githubusercontent.com/81793100/238908052-f0771c3c-2bdc-463c-a60d-9c40a6af5592.jpg)

Hi @alzihadi 

See `setDefaultCallerName` ([docs](https://github.com/diegogarciar/twilio_voice#default-caller)), or use `registerClient` ([docs](https://github.com/diegogarciar/twilio_voice#registering-a-client))

[Example implementation](https://github.com/diegogarciar/twilio_voice/blob/master/example/lib/main.dart#L113) & [iOS implementation](https://github.com/diegogarciar/twilio_voice/blob/master/ios/Classes/SwiftTwilioVoicePlugin.swift#L767)
