### ISSUE TITLE
Crash release build(signed apk) when user initiate call or accept call

### ISSUE THREAD

**Issue by PriyaSindkar** [cybex-dev/twilio_voice#6]
Having the following issue- https://github.com/twilio/voice-quickstart-android/issues/298

The proguard rules defined by you are just as suggested in the above git issue for Twilio voice SDK but still facing the issue. Can you please look into this and check if there is something we need to add in your plugin?

**Comment by diegogarciar** [comment]
Try creating a proguard-rules.pro with this content.

```
## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.**

# Twilio Programmable Voice
-keep class com.twilio.** { *; }
-keep class tvo.webrtc.** { *; }
-dontwarn tvo.webrtc.**
-keep class com.twilio.voice.** { *; }
-keepattributes InnerClasses

## Gson rules
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}
```

**Comment by PriyaSindkar** [comment]
Now not able to generated signed apk after adding this proguard rule.  Getting below error. 
![IMG_20210502_113022](https://user-images.githubusercontent.com/13249791/116806712-7690d700-ab4c-11eb-886c-952a47d7c0a9.jpg)

**Comment by yuszafar** [comment]
> Try creating a proguard-rules.pro with this content.
> 
> ```
> ## Flutter wrapper
> -keep class io.flutter.app.** { *; }
> -keep class io.flutter.plugin.**  { *; }
> -keep class io.flutter.util.**  { *; }
> -keep class io.flutter.view.**  { *; }
> -keep class io.flutter.**  { *; }
> -keep class io.flutter.plugins.**  { *; }
> -dontwarn io.flutter.embedding.**
> 
> # Twilio Programmable Voice
> -keep class com.twilio.** { *; }
> -keep class tvo.webrtc.** { *; }
> -dontwarn tvo.webrtc.**
> -keep class com.twilio.voice.** { *; }
> -keepattributes InnerClasses
> 
> ## Gson rules
> # Gson uses generic type information stored in a class file when working with fields. Proguard
> # removes such information by default, so configure it to keep all of it.
> -keepattributes Signature
> 
> # For using GSON @Expose annotation
> -keepattributes *Annotation*
> 
> # Gson specific classes
> -dontwarn sun.misc.**
> #-keep class com.google.gson.stream.** { *; }
> 
> # Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
> # JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
> -keep class * extends com.google.gson.TypeAdapter
> -keep class * implements com.google.gson.TypeAdapterFactory
> -keep class * implements com.google.gson.JsonSerializer
> -keep class * implements com.google.gson.JsonDeserializer
> 
> # Prevent R8 from leaving Data object members always null
> -keepclassmembers,allowobfuscation class * {
>   @com.google.gson.annotations.SerializedName <fields>;
> }
> ```

thanks. It works

**Comment by qburst-subins** [comment]
@diegogarciar Facing same issue even after setting the pro-guard file.
