### ISSUE TITLE
Exception in pushToCallScreen()

### ISSUE THREAD

**Issue by victor-padovam** [cybex-dev/twilio_voice#61]
When I get a call from another device, and I accept a call it calls the pushToCallScreen() function
which navigates to the CallScreen() screen.
In this he is generating an Exception.

![alt text](https://i.ibb.co/XJT4H8T/Captura-de-Tela-2021-12-01-a-s-10-59-58.png)

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
E/flutter ( 7929): Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.package:flutter/…/widgets/framework.dart:915
E/flutter ( 7929): #2      _DialScreenState.pushToCallScreen
package:twillio_voice_app/twillio_voice_call.dart:266
E/flutter ( 7929): #3      _DialScreenState.waitForCall.<anonymous closure>
package:twillio_voice_app/twillio_voice_call.dart:184
```

**Comment by Erchil66** [comment]
@VictorPadovan1997 Hi men can i ask how do you pass an inbound call using laravel? can you help me about it my access token is on outbound also on firebase how do you trigger it?.

**Comment by victor-padovam** [comment]
> @ VictorPadovan1997 Olá, rapaz, posso perguntar como é que passa uma chamada de entrada utilizando o laravel? você pode me ajudar com isso meu token de acesso está na saída e também no firebase como você o aciona ?.

Good afternoon. I did it with laravel, this deviates a little from the issue I opened, creates another Issue  on this subject and marks me that I answer.

**Comment by victor-padovam** [comment]
@cybex-dev any solution for my help.

**Comment by Erchil66** [comment]
@VictorPadovan1997  friend can i ask for your email i really need some guidance on twilio voice laravel and the flutter side to connect each other.

**Comment by victor-padovam** [comment]
Yes, 
victorpadovan1997@gmail.com

**Comment by cybex-dev** [comment]
> @cybex-dev any solution for my help.

hi @VictorPadovan1997 sorry for the late reply. There is a difference in widgets: stateless & stateful. 
 - **Stateless:** you won't see this problem, but chances are you wont use a stateless widget either. 
 - **Stateful** widgets, as the name suggests depends on an application state, also you rebuild the widget at times by calling `setState`. The issue working with stateful widgets and futures/async functions are the widget(s) may not exist in the widget tree anymore when the future's result has returned. You need to check to see if the widget is mounted when altering the state. To do this, you need to call.

```dart
if (mounted) {
    setState((){
        // call your actions
    });
}
```

See this for more info: https://api.flutter.dev/flutter/widgets/State/setState.html

**Comment by cybex-dev** [comment]
Closing due top lack of responses, feedback or activity.
