### ISSUE TITLE
appears 'Desconocido' in the background 

### ISSUE THREAD

**Issue by victor-padovam** [cybex-dev/twilio_voice#62]
When the app is completely closed, 'Disconocido' appears

![alt text](https://i.ibb.co/SX5NQGZ/Whats-App-Image-2021-12-01-at-15-04-57.jpg)

What did I do to resolve.

I made changes to the role **handleCallIntent** of the file **BackgroundCall....java**
(https://github.com/diegogarciar/twilio_voice/blob/master/android/src/main/java/com/twilio/twilio_voice/BackgroundCallJavaActivity.java#L99)

My solution to resolve this was.

in function:
`String caller = preferences.getString(fromId, preferences.getString("defaultCaller", "Desconocido"));
`
changed To: 
```
String fromId = intent.getStringExtra(Constants.CALL_FROM).replace("client:", "");
String caller = preferences.getString(fromId, preferences.getString("defaultCaller", fromId));
```

Result: 

![alt text](https://i.ibb.co/C75hTRr/Whats-App-Image-2021-12-01-at-15-06-06.jpg)

**Comment by diegogarciar** [comment]
Thanks I'll review this
