### ISSUE TITLE
help in setToken

### ISSUE THREAD

**Issue by victor-padovam** [cybex-dev/twilio_voice#66]
this function below as it would for IOS.
because for android I pass the deviceToken which would be the FCM token of the device.
and for IOS?

```
TwilioVoice.instance
          .setTokens(
        accessToken: updateToken,
        deviceToken: androidToken,
      )
```

**Comment by diegogarciar** [comment]
Please refer to the example project and the variable documentation

**Comment by diegogarciar** [comment]
iOS doesn't need to set the token as it is done internally, closing this for now
