### ISSUE TITLE
How to register a phone number that will be presented on background call screen

### ISSUE THREAD

**Issue by Yahllil** [cybex-dev/twilio_voice#68]
Hello,
I am trying to pass the phone number to TwilioVoice.instance.registerClient(...) in order to present the contact name instead of the number. But now, it always showing "Unknown caller" instead of showing the number.

How can we register a contact name for a phone number, and how can we achieve that when we don't have a contact connected to that number, the number itself will be presented instead of "Unknown caller"?

Thank you

**Comment by cybex-dev** [comment]
I'd suggest ensuring the client infact matches what you expect, review the code found [here](https://github.com/diegogarciar/twilio_voice/blob/master/android/src/main/java/com/twilio/twilio_voice/TwilioVoicePlugin.java#L448).

I'm working on a PR that will allow sending the caller name via TwiML application as a parameter that will automatically fill in on the call screen, making the pre-registration of a user redundant/not necessary.

**Comment by Yahllil** [comment]
I've tried TwilioVoice.instance.registerClient(...), but it seems it only works with a caller's userId (for example Firebase ID), and not with a regular phone number

**Comment by Yahllil** [comment]
Any update?

**Comment by cybex-dev** [comment]
> Any update?

Will be pushing PR in a day or so

**Comment by cybex-dev** [comment]
Hi @Yahllil placeholder resolution will be added with next release.

**Comment by cybex-dev** [comment]
Closing for now.
