### ISSUE TITLE
App Android crash when making or receiving call

### ISSUE THREAD

**Issue by lat233** [cybex-dev/twilio_voice#69]
Hi
I integrate twilio_voice 0.0.9 in my projetct Flutter 2.5.3
On iOS it is ok for making or receving call
However in Android, run as debug and release,  when making or receiving call, app crashes:
I've tested on real device (Samsung Galaxy J7 Android 9)

"f.j.a.b: Could not find 'libtwilio_voice_android_so.so'. Looked for: [armeabi-v7a, armeabi], but only found: [].
	at f.j.a.a.a(:173)
	at f.j.a.d.c(:180)
	at f.j.a.d.a(:136)
	at f.j.a.c.a(:70)
	at f.j.a.c.a(:51)
	at com.twilio.voice.Voice.loadLibrary(:1233)
	at com.twilio.voice.MediaFactory.instance(:31)
	at com.twilio.voice.LocalAudioTrack.create(:82)
	at com.twilio.voice.LocalAudioTrack.create(:29)
	at com.twilio.voice.Voice.connect(:573)
	at com.twilio.twilio_voice.TwilioVoicePlugin.onMethodCall(:442)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(:84)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:865)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:181)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by cybex-dev** [comment]
Take a look at this:

In short, you might need to add those ABIs to your project's `android/app/build.gradle` file (see [link](https://developer.android.com/games/optimize/64-bit) for more details).

something like:

```gradle
android {
    ...
    defaultConfig {
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }
    ...
}
```

_Note: add x86 if you use x86 images for emulators otherwise it won't work_

**Comment by lat233** [comment]
Thank you @cybex-dev but unfortunately it does not help
Here my gradle file:

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
   def keystorePropertiesFile = rootProject.file('key.properties')
   if (keystorePropertiesFile.exists()) {
       keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
   }

android {
    compileSdkVersion 30

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.xxx"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a","arm64-v8a","x86","x86_64"
        }
    }

    dependencies {
        implementation 'com.google.firebase:firebase-messaging:20.1.0'
    }

    flavorDimensions "app"
    productFlavors {
 
        client {
            dimension "app"
            applicationId "com.xxx.client"
            versionCode 1
            versionName "1.0"
        }
 
        driver {
            dimension "app"
            applicationId "com.xxx.driver"
            versionCode 5
            versionName "1.1.0"
        }
    }
    
     signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
           storePassword keystoreProperties['storePassword']
       }
   }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }

    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-messaging:20.1.0'
    implementation 'com.stripe:stripe-android:10.5.0'
    implementation 'io.card:android-sdk:5.+'
}

apply plugin: 'com.google.gms.google-services'

**Comment by lat233** [comment]
I update that it works on debug but not on release

**Comment by SR-INGENIOUSMINDSLAB** [comment]
You have to add Proguard file in Your app.
```
# Twilio Programmable Voice
-keep class com.twilio.** { *; }
-keep class tvo.webrtc.** { *; }
-dontwarn tvo.webrtc.**
-keep class com.twilio.voice.** { *; }
-keepattributes InnerClasses
```
Reference -: https://github.com/twilio/voice-quickstart-android/issues/298

**Comment by cybex-dev** [comment]
> You have to add Proguard file in Your app.
> 
> ```
> # Twilio Programmable Voice
> -keep class com.twilio.** { *; }
> -keep class tvo.webrtc.** { *; }
> -dontwarn tvo.webrtc.**
> -keep class com.twilio.voice.** { *; }
> -keepattributes InnerClasses
> ```
> 
> Reference -: [twilio/voice-quickstart-android#298](https://github.com/twilio/voice-quickstart-android/issues/298)

I've release to TestFlight and Playstore, I didn't have to add these rules. Regardless I'd be interested to see if it is needed.

@lat233 make sure that your `build.gradle` also references the `proguard` file.

**Comment by lat233** [comment]
Thank you so much @cybex-dev  and @SR-INGENIOUSMINDSLAB. It works !

I also found another solution that is not really "standard" but it works also:

By analyzing release and debug apk file, I found that libtwilio_voice_android_so.so does not exist in folders  /lib/armeabi-v7a and /lib/arm64-v8a of release apk but does in debug apk, so I copy this .so file to the folder /app/android/src/main/java/jniLibs and add this one in the gradle file

  sourceSets {
         main {
             jniLibs.srcDirs = ['src/main/jniLibs']
         }
    }

and 

dependencies {
  compile fileTree(dir: 'jniLibs', include: ['*.so'])
}

As the result, .so file is copied into right folder of release apk and it works
