### ISSUE TITLE
The toggleSpeaker does not work on iOS, when you use it, it never returns a Future

### ISSUE THREAD

**Issue by smartvipere75** [cybex-dev/twilio_voice#7]

**Comment by diegogarciar** [comment]
I was not able to reproduce your issue. Could you please test if the error is present in the example project? 
If it still fails, please provide me your flutter and dart version.

**Comment by smartvipere75** [comment]
> I was not able to reproduce your issue. Could you please test if the error is present in the example project?
> If it still fails, please provide me your flutter and dart version.

Hello, I haven't tested on example project but here are more details:
Flutter Version: 2.0.6
Dart Version: 2.12.3
iOS Version: 14.5
Device: iPhone X

Function that never returns:
`Future<bool?> toggleSpeaker(bool isOn) {
    return _voice.call.toggleSpeaker(isOn);
}`

Thank you.

**Comment by diegogarciar** [comment]
Hello I couldn't identify the issue, Can you test on the example project?

**Comment by smartvipere75** [comment]
> Hello I couldn't identify the issue, Can you test on the example project?

Hey, I found out the cause of the issue. So basically I was calling toggleSpeaker before the call status is connected. It's resolved now, you can close this issue now. Thank you.

**Comment by diegogarciar** [comment]
Cool, actually that's the reason I move the method to 'voice.call', but I forgot about that status detail! I'll add that to the docs
