### ISSUE TITLE
How do I get CallSId

### ISSUE THREAD

**Issue by ajay-drodify** [cybex-dev/twilio_voice#71]
Getting this exception 

`Unhandled Exception: MissingPluginException(No implementation found for method call-sid on channel twilio_voice/messages)`

**Comment by cybex-dev** [comment]
@diegogarciar I will check this out since it was a feature I implemented

**Comment by JCarlosR** [comment]
@cybex-dev I see latest version available in `pub.dev` is `0.0.9`.
Does it mean that your changes were not published yet?
As a temporary solution would it be fine to publish from master unofficially just for my own usage?
Thank you.

**Comment by cybex-dev** [comment]
@JCarlosR certainly, though you can use this repo (master) as it's already been merged.

`TwilioVoice.instance.call?.getSid()`

`CallSid` is part of the `TwilioCall` parameters.
