### ISSUE TITLE
[Feature] Add bluetooth support

### ISSUE THREAD

**Issue by cybex-dev** [cybex-dev/twilio_voice#73]
**Feature Suggestion**

Add Bluetooth sound/audio device support/manipulation - this allows users to switch between their preferred talking medium:
- phone
- speaker
- bluetooth

_I will try to add a PR with this, don't have anything scheduled yet._

**Comment by Yahllil** [comment]
Any news on that?

**Comment by cybex-dev** [comment]
@Yahllil non yet, on the todo list.

**Comment by cybex-dev** [comment]
#139

**Comment by cybex-dev** [comment]
Merged #151

**Comment by cybex-dev** [comment]
See [release 0.1.0](https://pub.dev/packages/twilio_voice/versions/0.1.0)
