### ISSUE TITLE
IOS / CallEvent.answer not showing

### ISSUE THREAD

**Issue by Erchil66** [cybex-dev/twilio_voice#78]
@cybex-dev @diegogarciar  i have a question  i can receive the incoming call but when i see on my logs i cant see the **CallEvent.answer** and it's already answered on the other side.

I was planning on create a timer to be run when the CallEvent.answer is triggred so that the timer will start running

**Comment by cybex-dev** [comment]
See: https://github.com/diegogarciar/twilio_voice/issues/70#issuecomment-1027745189

**Comment by Erchil66** [comment]
@cybex-dev  thanks.
