### ISSUE TITLE
Question about Fallback number

### ISSUE THREAD

**Issue by Erchil66** [cybex-dev/twilio_voice#79]
Queation : When Calling goes to Falback number, The One receiving call can't hear it the one who's calling but it's need the other side to click the speaker in order heard the voice come from the caller. is this an issue in callkit itself?

**Comment by diegogarciar** [comment]
Hello, what do you mean by fallback number?

**Comment by Erchil66** [comment]
@diegogarciar from twilio prod acc actually have a backup number which if the main number wasn't connected or being pick up goes to the back up number like +63 own my country which is also my second number which it might contact me

But am gonna close this i found some issue which when iphone goes call to android phone have quite a bug.

Thanks for replying.
