### ISSUE TITLE
Unknown Caller [IOS] 

### ISSUE THREAD

**Issue by Erchil66** [cybex-dev/twilio_voice#80]
Is there a way for me to change the default caller name in swift ios in my twilio result is my client is number and i want to replace the **client:** to **to_fullname** so that i can get the name not the number or the default unknown caller. Shows in CallKit and the Notification.

What/Where are do i start to change some code in the native swift? In order for me to achieve it?

**Comment by diegog-sf** [comment]
Hello, I think there's a function called

TwilioVoice.instance.setDefaultCallerName(String callerName)

**Comment by Erchil66** [comment]
@diegog-sf Hi. I would like to ask on the function 

TwilioVoice.instance.registerClient(id,name)
On the id part which id should be put does it any or id from  firebase or identity id or something i tried this but nothing works i do have lot of contacts to save. So tried registering them all.

**Comment by diegog-sf** [comment]
it would be the id you use for registering your user with twilio. I normally use firebase user id for my twilio users

**Comment by Erchil66** [comment]
@diegog-sf  thanks.

**Comment by Erchil66** [comment]
Am Closing this issue since the problem i have was the twiml side

**Comment by fthardik** [comment]
@Erchil66 what did you change?
