### ISSUE TITLE
Call is not Acceptable in background in Android 9 Infinix hot 8.

### ISSUE THREAD

**Issue by Ahmadgnoor** [cybex-dev/twilio_voice#81]
Call is not Acceptable in background in Android 9 Infinix hot 8. and also the Caller go back untill the Calle go to Call screen ..Please check and resolve this issue .... 
Also a request to update to kotline from java in android

**Comment by cybex-dev** [comment]
@Ahmadgnoor regarding first issue, could you explain in more detail what the problem is.

For Kotlin conversion request, feel free to submit a PR.

**Comment by cybex-dev** [comment]
@Ahmadgnoor I believe I replicated your problem, could you please confirm?
#140

**Comment by Ahmadgnoor** [comment]
Yes this issue is still exist

**Comment by cybex-dev** [comment]
@Ahmadgnoor thanks for the feedback - just to confirm whether #140 is infact what you're experiencing.

Also, as per your request, I'm in the process of rewriting into Kotlin.

**Comment by cybex-dev** [comment]
Check out #151 merged

**Comment by cybex-dev** [comment]
@Ahmadgnoor rewritten in Kotlin as requested.
See [release 0.1.0](https://pub.dev/packages/twilio_voice/versions/0.1.0)
