### ISSUE TITLE
Segmentation fault: 11 while archiving using Xcode

### ISSUE THREAD

**Issue by Yahllil** [cybex-dev/twilio_voice#82]
It seems this package (twilio_voice) causes the new iOS error: `Segmentation fault: 11` on Xcode 13.3.
Can you please take a look at solving this ASAP? Our app is dependent on this package

**Comment by diegog-sf** [comment]
I can look into it until tomorrow, your help is also appreciated

**Comment by Erchil66** [comment]
@diegog-sf   i also having some issue although mine is 

-- Error
    -- Abort trap: 6
    
 @Yahllil do you have some work around on this rather than downgrading xcode back to 13.2.1?

**Comment by Yahllil** [comment]
> @diegog-sf i also having some issue although mine is
> 
> -- Error -- Abort trap: 6
> 
> @Yahllil do you have some work around on this rather than downgrading xcode back to 13.2.1?

I've found that disabling bitcode in Xcode solved it. Not the best option, but seems fine until we'll have a permanent fix of the package

**Comment by Erchil66** [comment]
@Yahllil  were i can locate that ? disabling bitcode in Xcode .

**Comment by Yahllil** [comment]
> 

`Enable Bitcode` under build settings in Xcode

**Comment by cybex-dev** [comment]
Closing since this issue seems resolved.
