### ISSUE TITLE
Regarding Call status 

### ISSUE THREAD

**Issue by MathewsRony** [cybex-dev/twilio_voice#84]
During the call, if I go back or close the app in android. The call is in progress. we don't see anything regarding the call which is going on in android. We don't see anything call info like notification or any other info from which the user can access the call screen again.

**Comment by diegogarciar** [comment]
Hello, it seems a feature to terminate the call when the app closes is unimplemented, help is welcome!

**Comment by cybex-dev** [comment]
@MathewsRony thanks for reporting, I'll look to address this in the near future. If not the upcoming release, certainly the next.

**Comment by cybex-dev** [comment]
> During the call, if I go back or close the app in android. The call is in progress. we don't see anything regarding the call which is going on in android. We don't see anything call info like notification or any other info from which the user can access the call screen again.

This is in-development at the moment, implementing Android's version of CallKit (Connection Service). For a short-term solution, I'll be addressing this issue in the up-coming release.

**Comment by cybex-dev** [comment]
This might be similar to your experience, #140

**Comment by cybex-dev** [comment]
Check out #151 merged

**Comment by cybex-dev** [comment]
See [release 0.1.0](https://pub.dev/packages/twilio_voice/versions/0.1.0)
