### ISSUE TITLE
How can i make a conference Call using this Sdk...? any solution Please

### ISSUE THREAD

**Issue by Ahmadgnoor** [cybex-dev/twilio_voice#85]

**Comment by diegogarciar** [comment]
Hello, you can configure your server to create a conference call, you would just need to add a logic so that when a specific data is sent, it does that. i.e, caller id is conference id

**Comment by Ahmadgnoor** [comment]
Thank You for Reply
Sdk is not getting Event for participant and Please Guide me how i achive
that

**Comment by cybex-dev** [comment]
@Ahmadgnoor 
See this as a start - https://www.twilio.com/docs/voice/tutorials/how-to-create-conference-calls

**Comment by cybex-dev** [comment]
Closing for now.
If you have a suggestion for adding conferencing ability, feel free to open up, comment or submit a PR>
