### ISSUE TITLE
How to go in the CallKit when clicking above in-call

### ISSUE THREAD

**Issue by Erchil66** [cybex-dev/twilio_voice#86]
![image_from_ios](https://user-images.githubusercontent.com/92772509/160605670-96b4cfd6-5c81-4918-89d1-c03fe17bcd46.jpg)

Hello Guyz, Any Solution for this when trying to click the above that color green it's doing nothing.

i want is that when clicking the green button above then goes to here and am bit bind don't know where to start.
![Inkedimage_from_ios_720 (1)_LI](https://user-images.githubusercontent.com/92772509/160606326-6e5a4096-e36d-4c3b-8907-ca692d7159c3.jpg)

@diegogarciar  how can i achieve this?

**Comment by diegogarciar** [comment]
I think we have no control on what callkit does. If its not working probably its an iOS issue. I've seen this issue too with WhatsApp recently.

**Comment by Erchil66** [comment]
@diegogarciar yeah i think also thanks for the reply an sorry for my late reply am gonna close this issue
