### ISSUE TITLE
where put my Api in flutter app

### ISSUE THREAD

**Issue by irfannn2** [cybex-dev/twilio_voice#87]
Hi please please help me I don't understand where put my twilio Api in flutter app. Someone tel me please

**Comment by diegogarciar** [comment]
It should be configured on your server. Please check Twilio quickstart docs. I suggest you run a native example app first and once you get it working, you migrate to flutter.

**Comment by irfannn2** [comment]
Can you make video for me I don't understand please please

**Comment by diegogarciar** [comment]
I can configure the project for you, but it will cost you around $400.
For free I can give you this
https://www.twilio.com/docs/voice/sdks/ios/get-started
