### ISSUE TITLE
I can't answer incoming call when app is closed completely 

### ISSUE THREAD

**Issue by MathewsRony** [cybex-dev/twilio_voice#88]
I'm using Android 11
I am getting an incoming call notification when the app is completely closed but nothing is happening when I try to click the answer button in the notification. and if I click on the notification incoming call screen pop up and when I click the answer button popup closes and nothing is happening. I want the flutter app to open like normal notifications and answer the call.

**Comment by Ahmadgnoor** [comment]
Same issue

**Comment by TheVinhLuong** [comment]
I tried out this fork and it is working https://github.com/cybex-dev/twilio_voice/tree/master

**Comment by cybex-dev** [comment]
@TheVinhLuong thanks for using my fork, though I'll be merging changes from there into this main repo.
Closing for now.
