### ISSUE TITLE
Incoming call is misspelled as 'Incomming' for Android

### ISSUE THREAD

**Issue by paramvirgill** [cybex-dev/twilio_voice#89]
![image000000](https://user-images.githubusercontent.com/17292901/164367146-31b64133-7054-4370-a2c9-fc7a6933b466.jpg)

Any way this could be fixed?

**Comment by cybex-dev** [comment]
Hi @paramvirgill - by fixed, what do you have in mind?

**Comment by tanmoy27112000** [comment]
changing it to 'incoming call....' will fix it

**Comment by cybex-dev** [comment]
@tanmoy27112000 certainly - I could put out an expedited fix for this. This UI should be done away with in the near future as soon as I finish the new ConnectionService impl for Android.

**Comment by cybex-dev** [comment]
#126

**Comment by cybex-dev** [comment]
Addressing in upcoming release. ConnectionService (Android's CallKit) update may be available in the next update.

**Comment by cybex-dev** [comment]
Check out #151 merged

**Comment by cybex-dev** [comment]
See [release 0.1.0](https://pub.dev/packages/twilio_voice/versions/0.1.0)
