### ISSUE TITLE
About the callkit icon

### ISSUE THREAD

**Issue by mi6ock** [cybex-dev/twilio_voice#9]
Hi.
I'd like to set the image for the button leading to the app that appears in the CallKit call UI.
Maybe this image can't be changed?
Looking at the source code, it doesn't look like it can be changed.

https://github.com/diegogarciar/twilio_voice/blob/3dc3a63bb78be224144861cb6e1dfb1421ba3b59/ios/Classes/SwiftTwilioVoicePlugin.swift#L58-L60

**Comment by diegogarciar** [comment]
Sure, it can be changed by adding an image with the same name by opening xcode and adding it to your assets.xassets folder. I’ll add this to the docs!

**Comment by diegogarciar** [comment]
Did this solved your issue?

**Comment by mi6ock** [comment]
Solved. 
Thanks!

**Comment by diegogarciar** [comment]
Actually I will rename the icon to something more meaningful, so I suggest you create a copy of the icon and name it callkit_icon for when the change kicks in.

**Comment by diegogarciar** [comment]
FYI, Icon name was successfully changed in 0.0.8 to callkit_icon. Added this to docs
