### ISSUE TITLE
How can I register multiple clients (Name and Number), many of which won't be installing the app?

### ISSUE THREAD

**Issue by paramvirgill** [cybex-dev/twilio_voice#91]
The idea is to show caller ID's on incoming calls but most callers won't be using the app. So, what would be the best way to show their names? API call on incoming or pre-registering them? If latter, then on the backend level (Python Django) or frontend (flutter) and how?

**Comment by cybex-dev** [comment]
@paramvirgill this wouldn't make sense to store hundreds, or thousands of entries.

Rather, I'm working on a feature to dynamically update the caller screens with names using specific placeholders, parsing the call parameters to show names, etc on the call screens.

Will be available in the next release.

**Comment by cybex-dev** [comment]
Closing for now.
