### ISSUE TITLE
When app is closed only vibration % ringing. There is no Call Screen UI or Intent Triggered...any solution

### ISSUE THREAD

**Issue by Ahmadgnoor** [cybex-dev/twilio_voice#94]
If App is Open or in background the Incoming Call screen or Notification working, But when app is closed only vibaration and Ringing No UI, Please help to sort Out

**Comment by cybex-dev** [comment]
@Ahmadgnoor this comes through as a call (Heads Up) notification only if the phone is unlocked. If locked/sleeping, the call screen shows.

**Comment by cybex-dev** [comment]
@Ahmadgnoor you're more than welcome to submit a PR, feature request, etc.

I will keep this in mind when making Android changes.

**Comment by cybex-dev** [comment]
Closing for now.

**Comment by cybex-dev** [comment]
#140

**Comment by cybex-dev** [comment]
Seems I was able to replicate this issue after recent testing - will look into it.

**Comment by cybex-dev** [comment]
Check out #151 merged

**Comment by cybex-dev** [comment]
See [release 0.1.0](https://pub.dev/packages/twilio_voice/versions/0.1.0)
