### ISSUE TITLE
Android 12 , problem 

### ISSUE THREAD

**Issue by mazen930** [cybex-dev/twilio_voice#96]
Whenever i try to install flutter on Samsung mobile with android 12 , it throw the following error
`       android:exported needs to be explicitly specified for element <service#com.twilio.twilio_voice.IncomingCallNotificationService>. Apps targeting Android 12 and higher are required to specify an explicit value for android:exported when the corresponding component has an intent filter defined `
however i didn't add this service , so Any help ?

**Comment by mazen930** [comment]
What helps me is to add this dependencies :
`  firebase_core: ^1.8.0
  firebase_messaging: ^10.0.9
  cloud_functions: ^3.0.5
  firebase_auth: ^3.1.4`
  not sure tho how they are related to the issue (you can find them in example provided in the repo)

**Comment by nawafAlkhadidi** [comment]
same issues

**Comment by Erchil66** [comment]
![image](https://user-images.githubusercontent.com/92772509/197176633-480b6b50-b639-46df-b573-27ad59e6a4a1.png)

Fork the project goto the android manifest add this android:exported="false|true"

**Comment by mazen930** [comment]
@Erchil66  That's really helps and make things more clear

**Comment by carman247** [comment]
Can also be necessary to add ```android:exported="true"``` to the service added to the manifest in the mobile app as well
