### ISSUE TITLE
ANDROID 10, 11, 12 speaker always remain opened

### ISSUE THREAD

**Issue by Ahmadgnoor** [cybex-dev/twilio_voice#97]
when call started call voice is coming out even the speaker is disabled ... on enable or disable voice volume remain same loud

**Comment by CassadyCam** [comment]
Was this issue resolved?

**Comment by cybex-dev** [comment]
See PR #102 (currently in draft), should be available in next release.

**Comment by cybex-dev** [comment]
Closing for now.
