### ISSUE TITLE
access token can not be null, and display still showing connecting.

### ISSUE THREAD

**Issue by maazuddin799** [cybex-dev/twilio_voice#98]

**Comment by CassadyCam** [comment]
Access token can not be null sounds like you are not retrieving and setting your access token that should be generated from firebase. 

You can debug your program and see what is being returned from firebase. Most likely you have a configuration issue and the call is not returning anything. 

See the example
Line 58 makes the call for the access token from firebase
Line 66-67 sets the access token to Twilio
![image](https://user-images.githubusercontent.com/103965536/175056983-f2c241ef-438f-480e-be95-0522f0317860.png)

**Comment by cybex-dev** [comment]
Closing due top lack of responses, feedback or activity.
