### ISSUE TITLE
Mobile phone is locked then call is not working properly not mic or not speaker

### ISSUE THREAD

**Issue by Ahmadgnoor** [cybex-dev/twilio_voice#99]
Mobile phone is locked then call is not working properly not mic or not speaker

**Comment by cybex-dev** [comment]
@Ahmadgnoor I have a PR #102 to resolve these issues.

**Comment by cybex-dev** [comment]
@Ahmadgnoor this would also happen if you didn't request permissions e.g. iOS app w/ callkit.

**Comment by cybex-dev** [comment]
Closing due top lack of responses, feedback or activity.
